import { supabase } from "./supabase";
import type { AnalyticsEvent, AnalyticsSummary, Business, BusinessBundle, BusinessForm, BusinessLink, BusinessMedia, Profile } from "./types";
export const dbError = "Conecte o Supabase para carregar dados reais. Configure VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY (ou VITE_SUPABASE_ANON_KEY legado).";
function requireDb() { if (!supabase) throw new Error(dbError); return supabase; }
export async function listBusinesses() { const { data, error } = await requireDb().from("businesses").select("*").order("created_at", { ascending: false }); if (error) throw error; return (data ?? []) as Business[]; }
export async function getBusinessBySlug(slug: string, publishedOnly = true) { const db = requireDb(); let query = db.from("businesses").select("*, business_links(*), business_media(*)").eq("slug", slug); if (publishedOnly) query = query.eq("status", "published"); const { data, error } = await query.maybeSingle(); if (error) throw error; if (!data) return null; return { business: data as Business, links: ((data as any).business_links ?? []).sort((a: BusinessLink, b: BusinessLink) => a.position - b.position), media: ((data as any).business_media ?? []).sort((a: BusinessMedia, b: BusinessMedia) => a.position - b.position) } as BusinessBundle; }
export async function getBusiness(id: string) { const { data, error } = await requireDb().from("businesses").select("*, business_links(*), business_media(*)").eq("id", id).single(); if (error) throw error; return data as Business & { business_links?: BusinessLink[]; business_media?: BusinessMedia[]; }; }
export async function saveBusiness(form: BusinessForm, id?: string) { const db = requireDb(); const payload = { name: form.name.trim(), slug: form.slug.trim(), logo_url: form.logo_url || null, tagline: form.tagline.trim() || "Olá! Como podemos ajudar?", google_review_url: form.google_review_url || null, whatsapp_number: form.whatsapp_number || null, whatsapp_message: form.whatsapp_message || null, instagram_url: form.instagram_url || null, website_url: form.website_url || null, address: form.address || null, maps_url: form.maps_url || null, primary_color: form.primary_color, secondary_color: form.secondary_color, background_color: form.background_color, background_image_url: form.background_image_url || null, standard_button_color: form.standard_button_color, custom_button_color: form.custom_button_color, seo_title: form.seo_title || null, seo_description: form.seo_description || null, seo_image_url: form.seo_image_url || null };
  const result = id ? await db.from("businesses").update(payload).eq("id", id).select().single() : await db.from("businesses").insert({ ...payload, created_by: (await db.auth.getUser()).data.user?.id }).select().single(); if (result.error) throw result.error; const business = result.data as Business; await db.from("business_links").delete().eq("business_id", business.id); if (form.links.length) { const { error } = await db.from("business_links").insert(form.links.map((link, position) => ({ business_id: business.id, label: link.label, url: link.url, kind: link.kind, color: link.color, position }))); if (error) throw error; } await db.from("business_media").delete().eq("business_id", business.id); if (form.media.length) { const { error } = await db.from("business_media").insert(form.media.map((media, position) => ({ business_id: business.id, type: media.type, url: media.url, storage_path: media.storage_path ?? null, alt: media.alt, position }))); if (error) throw error; } return business; }
export async function setBusinessStatus(id: string, status: "draft" | "inactive") { const { error } = await requireDb().from("businesses").update({ status }).eq("id", id); if (error) throw error; }
export async function publishBusiness(id: string) { const { error } = await requireDb().from("businesses").update({ status: "published", published_at: new Date().toISOString() }).eq("id", id); if (error) throw error; }
export async function deleteBusiness(id: string) { const { error } = await requireDb().from("businesses").delete().eq("id", id); if (error) throw error; }
export async function uploadAsset(file: File, businessId: string, kind: "logo" | "background" | "media") { const db = requireDb(); const safe = file.name.toLowerCase().replace(/[^a-z0-9.]+/g, "-"); const path = `${businessId}/${kind}/${crypto.randomUUID()}-${safe}`; const { error } = await db.storage.from("business-assets").upload(path, file, { cacheControl: "31536000", upsert: false, contentType: file.type }); if (error) throw error; const { data } = db.storage.from("business-assets").getPublicUrl(path); return { url: data.publicUrl, path }; }
export async function trackEvent(event: AnalyticsEvent) { if (!supabase) return; await supabase.from("analytics_events").insert(event); }
export async function getAnalytics(businessId: string, days: number): Promise<AnalyticsSummary> { const start = new Date(Date.now() - days * 86400000).toISOString(); const { data, error } = await requireDb().from("analytics_events").select("*").eq("business_id", businessId).gte("created_at", start); if (error) throw error; const rows = (data ?? []) as (AnalyticsEvent & { created_at: string })[]; const views = rows.filter(r => r.event_type === "view").length; const clicks = rows.filter(r => r.event_type === "click").length; const daysSet = new Set(rows.map(r => r.created_at.slice(0, 10))); const devices = { mobile: 0, tablet: 0, desktop: 0 }; const sources = { instagram: 0, whatsapp: 0, google: 0, placa: 0, direct: 0, other: 0 }; const clickMap = new Map<string, number>(); rows.forEach(r => { devices[r.device_type] += 1; sources[r.source] += 1; if (r.event_type === "click") clickMap.set(r.target, (clickMap.get(r.target) ?? 0) + 1); }); const dailyMap = new Map<string, number>(); rows.filter(r => r.event_type === "view").forEach(r => dailyMap.set(r.created_at.slice(0, 10), (dailyMap.get(r.created_at.slice(0, 10)) ?? 0) + 1)); const daily = Array.from({ length: days }, (_, index) => { const date = new Date(Date.now() - (days - index - 1) * 86400000).toISOString().slice(0, 10); return { day: date, views: dailyMap.get(date) ?? 0 }; }); return { views, clicks, uniqueDays: daysSet.size, devices, sources, daily, topClicks: Array.from(clickMap.entries()).map(([target, count]) => ({ target, count })).sort((a, b) => b.count - a.count).slice(0, 5) }; }
export async function currentProfile() { const db = requireDb(); const { data: auth } = await db.auth.getUser(); if (!auth.user) return null; const { data, error } = await db.from("profiles").select("*").eq("id", auth.user.id).single(); if (error) throw error; return data as Profile; }
export async function listProfiles() { const { data, error } = await requireDb().from("profiles").select("*").order("created_at", { ascending: false }); if (error) throw error; return (data ?? []) as Profile[]; }
export async function updateProfileAccess(id: string, access_status: "approved" | "revoked") { const { error } = await requireDb().from("profiles").update({ access_status }).eq("id", id); if (error) throw error; }
export async function updateProfileRole(id: string, role: "user" | "admin") { const { error } = await requireDb().from("profiles").update({ role }).eq("id", id); if (error) throw error; }
export async function removeProfile(id: string) { const { error } = await requireDb().from("profiles").delete().eq("id", id); if (error) throw error; }
