import type { BusinessForm } from "./types";

export type TemplateCategory = "Gastronomia" | "Beleza" | "Serviços" | "Varejo" | "Criativo";
export interface TemplatePreset { id: string; name: string; category: TemplateCategory; description: string; tone: string; form: BusinessForm; isCustom?: boolean; }

const features = (catalog_text: string, testimonials_text: string, campaign_title = "", campaign_text = ""): BusinessForm["features"] => ({ lead_enabled: true, lead_title: "Fale com a gente", lead_button: "Enviar mensagem", campaign_enabled: Boolean(campaign_text), campaign_title, campaign_text, campaign_cta: "Saiba mais", campaign_url: "", catalog_text, testimonials_text, qr_label: "PLAK", show_badge: true });
const visual = (category: TemplateCategory, index: number) => {
  const refs = category === "Criativo" ? ["creator-reference.png", "creator-reference.png"] : category === "Beleza" ? ["business-card-reference.webp", "business-card-reference.webp"] : ["bajor-reference.png", "bajor-reference.png"];
  const avatars = category === "Criativo" ? ["profile-creator.png", "profile-creator.png"] : category === "Beleza" ? ["profile-beauty.webp", "profile-beauty.webp"] : ["profile-business.png", "profile-business.png"];
  const image = `/template-references/${refs[index % refs.length]}`;
  const avatar = `/template-references/${avatars[index % avatars.length]}`;
  return { logo_url: avatar, background_image_url: image, media: [{ type: "image" as const, url: image, alt: "Imagem de apresentação do modelo", position: 0 }, { type: "image" as const, url: avatar, alt: "Foto de perfil do modelo", position: 1 }] };
};
const base = (values: Partial<BusinessForm>, category: TemplateCategory, index: number): BusinessForm => ({
  name: "", slug: "", tagline: "Sua marca, em um toque.", google_review_url: "https://g.page/", whatsapp_number: "5511999999999", whatsapp_message: "Olá! Vim pela página da marca.", instagram_url: "https://instagram.com/", website_url: "https://plak.app", address: "Rua principal, 100 · Centro", maps_url: "https://maps.google.com", primary_color: "#17262D", secondary_color: "#D8EE77", background_color: "#F4F6F1", standard_button_color: "#FFFFFF", custom_button_color: "#D8EE77", seo_title: "", seo_description: "", seo_image_url: "", features: features("Serviço principal | Uma experiência pensada para você | A partir de R$ 80\nAtendimento especial | Fale com a nossa equipe | Consulte", "Marina | Atendimento impecável e muito rápido."), links: [{ label: "Agende ou peça pelo WhatsApp", url: "https://wa.me/5511999999999", kind: "whatsapp", color: "#17262D", position: 0 }, { label: "Veja nosso Instagram", url: "https://instagram.com/", kind: "site", color: "#FFFFFF", position: 1 }, { label: "Como chegar", url: "https://maps.google.com", kind: "maps", color: "#FFFFFF", position: 2 }], ...visual(category, index), ...values,
});
const preset = (id: string, name: string, category: TemplateCategory, description: string, tone: string, values: Partial<BusinessForm>, index: number): TemplatePreset => ({ id, name, category, description, tone, form: base(values, category, index) });

export const templatePresets: TemplatePreset[] = [
  preset("bio-restaurante-bistro", "Bistrô Elegante", "Gastronomia", "Bio site sofisticado com cardápio, reservas, WhatsApp e localização.", "#C9A66B", { name: "Bistrô Aurora", slug: "bistro-aurora", tagline: "Uma experiência especial a cada prato.", primary_color: "#30251F", secondary_color: "#C9A66B", background_color: "#F8F2E9", features: features("Menu executivo | Entrada, prato principal e sobremesa | R$ 59\nPratos da casa | Receitas autorais com ingredientes frescos | A partir de R$ 42", "Marina | Ambiente acolhedor e comida maravilhosa."), links: [{ label: "Reservar uma mesa", url: "https://wa.me/5511999999999", kind: "whatsapp", color: "#30251F", position: 0 }, { label: "Ver cardápio", url: "https://wa.me/5511999999999", kind: "whatsapp", color: "#C9A66B", position: 1 }, { label: "Como chegar", url: "https://maps.google.com", kind: "maps", color: "#FFFFFF", position: 2 }] }, 0),
  preset("bio-hamburgueria-urbana", "Hamburgueria Urbana", "Gastronomia", "Visual marcante para divulgar combos, delivery e pedidos rápidos.", "#F2B544", { name: "Brasa Burger", slug: "brasa-burger", tagline: "Hambúrguer de verdade. Fome resolvida.", primary_color: "#211D1A", secondary_color: "#F2B544", background_color: "#FFF7E8", features: features("Smash clássico | Dois smash burgers, queijo e molho da casa | R$ 29,90\nCombo Brasa | Burger, batata crocante e bebida | R$ 42,90", "Lucas | Chegou quentinho e estava muito bom."), links: [{ label: "Pedir pelo WhatsApp", url: "https://wa.me/5511999999999", kind: "whatsapp", color: "#211D1A", position: 0 }, { label: "Ver o cardápio", url: "https://wa.me/5511999999999", kind: "whatsapp", color: "#F2B544", position: 1 }, { label: "Instagram", url: "https://instagram.com/", kind: "site", color: "#FFFFFF", position: 2 }] }, 1),
  preset("bio-pizzaria-familia", "Pizzaria da Família", "Gastronomia", "Bio site acolhedor com sabores, promoções e botão para pedir.", "#B84332", { name: "Forno da Vila", slug: "forno-da-vila", tagline: "Da nossa família para a sua mesa.", primary_color: "#6F2A22", secondary_color: "#B84332", background_color: "#FFF5EA", features: features("Margherita | Muçarela, tomate, manjericão e azeite | R$ 39\nCalabresa especial | Calabresa, cebola roxa e orégano | R$ 45", "Paulo | Massa excelente e atendimento atencioso."), links: [{ label: "Pedir pizza", url: "https://wa.me/5511999999999", kind: "whatsapp", color: "#6F2A22", position: 0 }, { label: "Conhecer os sabores", url: "https://wa.me/5511999999999", kind: "whatsapp", color: "#B84332", position: 1 }, { label: "Área de entrega", url: "https://maps.google.com", kind: "maps", color: "#FFFFFF", position: 2 }] }, 0),
  preset("bio-sushi-japones", "Sushi & Cozinha Japonesa", "Gastronomia", "Estilo limpo para combos, delivery, reservas e redes sociais.", "#C95E50", { name: "Sakura Sushi", slug: "sakura-sushi", tagline: "Frescor, cuidado e sabor em cada peça.", primary_color: "#242B29", secondary_color: "#C95E50", background_color: "#F5F3EE", features: features("Combo Sakura | Seleção de 20 peças variadas | R$ 59,90\n combinado especial | 30 peças do chef | R$ 89,90", "Beatriz | Peças frescas e apresentação impecável."), links: [{ label: "Pedir delivery", url: "https://wa.me/5511999999999", kind: "whatsapp", color: "#242B29", position: 0 }, { label: "Ver combinados", url: "https://wa.me/5511999999999", kind: "whatsapp", color: "#C95E50", position: 1 }, { label: "Reservar mesa", url: "https://wa.me/5511999999999", kind: "whatsapp", color: "#FFFFFF", position: 2 }] }, 1),
  preset("bio-cafe-padaria", "Café & Padaria Artesanal", "Gastronomia", "Página leve para cafés, brunch, encomendas e produtos do dia.", "#D6A16D", { name: "Manhã & Grão", slug: "manha-e-grao", tagline: "Pequenos momentos, feitos com carinho.", primary_color: "#5B4030", secondary_color: "#D6A16D", background_color: "#FBF4E9", features: features("Café coado | Grãos especiais preparados na hora | R$ 9\nPão de fermentação natural | Casca crocante e miolo macio | R$ 18\nBrunch da casa | Café, pão artesanal e bolo do dia | R$ 34", "Lúcia | Café delicioso e tudo sempre fresquinho."), links: [{ label: "Ver menu e encomendas", url: "https://wa.me/5511999999999", kind: "whatsapp", color: "#5B4030", position: 0 }, { label: "Pedir pelo WhatsApp", url: "https://wa.me/5511999999999", kind: "whatsapp", color: "#D6A16D", position: 1 }, { label: "Como chegar", url: "https://maps.google.com", kind: "maps", color: "#FFFFFF", position: 2 }] }, 0),
];
