import type { BusinessForm } from "./types";

export type TemplateCategory = "Gastronomia" | "Beleza" | "Serviços" | "Varejo" | "Criativo";
export interface TemplatePreset { id: string; name: string; category: TemplateCategory; description: string; tone: string; form: BusinessForm; }

const base = (values: Partial<BusinessForm>): BusinessForm => ({
  name: "", slug: "", logo_url: "", tagline: "Olá! Como podemos ajudar?", google_review_url: "", whatsapp_number: "", whatsapp_message: "Olá! Vim pela página da marca.", instagram_url: "", website_url: "", address: "", maps_url: "", primary_color: "#0F766E", secondary_color: "#F2B84B", background_color: "#FBFAF6", background_image_url: "", standard_button_color: "#FFFFFF", custom_button_color: "#FFFFFF", seo_title: "", seo_description: "", seo_image_url: "", features: { lead_enabled: false, lead_title: "Fale com a gente", lead_button: "Enviar mensagem", campaign_enabled: false, campaign_title: "", campaign_text: "", campaign_cta: "Saiba mais", campaign_url: "", catalog_text: "", testimonials_text: "", qr_label: "PLAK", show_badge: true }, links: [], media: [], ...values,
});

const preset = (id: string, name: string, category: TemplateCategory, description: string, tone: string, values: Partial<BusinessForm>): TemplatePreset => ({ id, name, category, description, tone, form: base(values) });

export const templatePresets: TemplatePreset[] = [
  preset("cafe-editorial", "Café Editorial", "Gastronomia", "Cardápio, reservas e localização com presença sofisticada.", "#D7F878", { name: "Café Aurora", slug: "cafe-aurora", tagline: "Café bom, conversa melhor.", primary_color: "#263B35", secondary_color: "#D7F878", background_color: "#F5F1E8" }),
  preset("restaurante-contemporaneo", "Restaurante Contemporâneo", "Gastronomia", "Uma página direta para reservas, menu e avaliações.", "#F2B84B", { name: "Casa Noma", slug: "casa-noma", tagline: "Sabores que ficam na memória.", primary_color: "#8A3D2E", secondary_color: "#F2B84B", background_color: "#FBF6EF" }),
  preset("bakery-soft", "Padaria Afetiva", "Gastronomia", "Visual acolhedor para mostrar produtos e receber pedidos.", "#E9A56B", { name: "Manhã & Trigo", slug: "manha-e-trigo", tagline: "Pão quente para dias melhores.", primary_color: "#9B5C3D", secondary_color: "#E9A56B", background_color: "#FFF8EE" }),
  preset("barber-dark", "Barbearia Dark", "Beleza", "Agenda e contato com identidade escura e masculina.", "#D7F878", { name: "North Barber", slug: "north-barber", tagline: "Corte preciso. Estilo próprio.", primary_color: "#17262D", secondary_color: "#D7F878", background_color: "#F0F3EE" }),
  preset("beauty-minimal", "Beauty Minimal", "Beleza", "Experiência delicada para salão, estética ou nail designer.", "#E8A9B8", { name: "Lume Beauty", slug: "lume-beauty", tagline: "Seu tempo de cuidado começa aqui.", primary_color: "#8D5667", secondary_color: "#E8A9B8", background_color: "#FFF7F5" }),
  preset("studio-skin", "Clínica Glow", "Beleza", "Agendamento, localização e redes em uma página limpa.", "#B6D8C2", { name: "Glow Studio", slug: "glow-studio", tagline: "Pele saudável, beleza real.", primary_color: "#356A5D", secondary_color: "#B6D8C2", background_color: "#F1F8F3" }),
  preset("architect", "Arquiteto Portfolio", "Serviços", "Apresente projetos, contato e posicionamento profissional.", "#D7F878", { name: "Traço Norte", slug: "traco-norte", tagline: "Espaços com intenção.", primary_color: "#1F3439", secondary_color: "#D7F878", background_color: "#F4F5F1" }),
  preset("law-office", "Escritório Essencial", "Serviços", "Contato rápido e credibilidade para serviços especializados.", "#C5A46D", { name: "Moraes & Lima", slug: "moraes-lima", tagline: "Clareza para decisões importantes.", primary_color: "#243A4A", secondary_color: "#C5A46D", background_color: "#F5F5F2" }),
  preset("consultant", "Consultoria Direct", "Serviços", "Uma página objetiva para captar conversas e reuniões.", "#79B8C9", { name: "Núcleo Estratégia", slug: "nucleo-estrategia", tagline: "Ideias claras. Próximos passos.", primary_color: "#15566A", secondary_color: "#79B8C9", background_color: "#F1F7F8" }),
  preset("real-estate", "Imobiliária Premium", "Serviços", "Link rápido para atendimento, imóveis e localização.", "#D5B46B", { name: "Casa Alta", slug: "casa-alta", tagline: "Encontre o lugar certo para viver.", primary_color: "#384B45", secondary_color: "#D5B46B", background_color: "#F6F3EC" }),
  preset("local-shop", "Loja Local", "Varejo", "Mostre a coleção e direcione clientes para o atendimento.", "#F39B72", { name: "Ponto & Forma", slug: "ponto-e-forma", tagline: "Peças escolhidas para o seu dia.", primary_color: "#9A4939", secondary_color: "#F39B72", background_color: "#FFF6F0" }),
  preset("fashion-label", "Marca de Moda", "Varejo", "Página editorial para coleção, Instagram e loja online.", "#D7F878", { name: "Forma 01", slug: "forma-01", tagline: "Vista o que faz sentido.", primary_color: "#111A1D", secondary_color: "#D7F878", background_color: "#F2F3EE" }),
  preset("florist", "Floricultura Botânica", "Varejo", "Visual orgânico para pedidos, catálogo e mensagens.", "#A9D3A4", { name: "Verde Vivo", slug: "verde-vivo", tagline: "Flores para dizer sem palavras.", primary_color: "#356344", secondary_color: "#A9D3A4", background_color: "#F2F8F0" }),
  preset("pet-care", "Pet Care", "Serviços", "Banho, tosa e contato em um fluxo simples para tutores.", "#F7B45A", { name: "Patas & Companhia", slug: "patas-companhia", tagline: "Cuidado que eles sentem.", primary_color: "#A95D36", secondary_color: "#F7B45A", background_color: "#FFF8ED" }),
  preset("fitness", "Studio Fitness", "Serviços", "Aulas, horários e contato com energia visual.", "#C8E343", { name: "Pulse Studio", slug: "pulse-studio", tagline: "Movimente o seu melhor.", primary_color: "#17262D", secondary_color: "#C8E343", background_color: "#EEF3EC" }),
  preset("photographer", "Fotógrafo Portfolio", "Criativo", "Portfólio visual com contato e redes em destaque.", "#D8C4FF", { name: "Mira Foto", slug: "mira-foto", tagline: "Histórias que merecem ficar.", primary_color: "#4C3B65", secondary_color: "#D8C4FF", background_color: "#F7F4FB" }),
  preset("music-artist", "Artista Musical", "Criativo", "Lançamentos, agenda e links essenciais para fãs.", "#F08BA8", { name: "Lia Nova", slug: "lia-nova", tagline: "Som para atravessar a noite.", primary_color: "#572943", secondary_color: "#F08BA8", background_color: "#FFF3F7" }),
  preset("event-planner", "Eventos & Festas", "Criativo", "Orçamentos, portfólio e contato para transformar ideias em eventos.", "#E8C875", { name: "Vértice Eventos", slug: "vertice-eventos", tagline: "Seu momento, do seu jeito.", primary_color: "#5C4A26", secondary_color: "#E8C875", background_color: "#FCF8EE" }),
  preset("creator", "Creator Hub", "Criativo", "Central de links para conteúdo, comunidade e parcerias.", "#8BD5E8", { name: "Nexo Creator", slug: "nexo-creator", tagline: "Tudo o que eu crio, em um toque.", primary_color: "#15566A", secondary_color: "#8BD5E8", background_color: "#F0FAFC" }),
  preset("community", "Comunidade Local", "Criativo", "Conecte pessoas, agenda, redes e pontos de encontro.", "#D7F878", { name: "Bairro Vivo", slug: "bairro-vivo", tagline: "Mais perto de quem importa.", primary_color: "#315B4B", secondary_color: "#D7F878", background_color: "#F1F7EF" }),
];
