import type { BusinessForm } from "./types";

export type TemplateCategory = "Gastronomia" | "Beleza" | "Serviços" | "Varejo" | "Criativo";
export interface TemplatePreset { id: string; name: string; category: TemplateCategory; description: string; tone: string; form: BusinessForm; isCustom?: boolean; }

const features = (catalog_text: string, testimonials_text: string, campaign_title = "", campaign_text = ""): BusinessForm["features"] => ({ lead_enabled: true, lead_title: "Fale com a gente", lead_button: "Enviar mensagem", campaign_enabled: Boolean(campaign_text), campaign_title, campaign_text, campaign_cta: "Saiba mais", campaign_url: "", catalog_text, testimonials_text, qr_label: "PLAK", show_badge: true });
const visual = (category: TemplateCategory, index: number) => {
  const refs = category === "Criativo" ? ["creator-reference.png", "creator-reference.png"] : category === "Beleza" ? ["business-card-reference.webp", "business-card-reference.webp"] : ["bajor-reference.png", "bajor-reference.png"];
  const avatars = category === "Criativo" ? ["profile-creator.png", "profile-creator.png"] : category === "Beleza" ? ["profile-beauty.webp", "profile-beauty.webp"] : ["profile-business.png", "profile-business.png"];
  const image = `/template-references/${refs[index % refs.length]}`;
  const avatar = `/template-references/${avatars[index % avatars.length]}`;
  return { logo_url: avatar, background_image_url: image, media: [{ type: "image" as const, url: image, alt: "Imagem de apresentação do modelo", position: 0 }, { type: "image" as const, url: avatar, alt: "Foto de perfil do modelo", position: 1 }] };
};
const base = (values: Partial<BusinessForm>, category: TemplateCategory, index: number): BusinessForm => ({
  name: "", slug: "", tagline: "Sua marca, em um toque.", google_review_url: "https://g.page/", whatsapp_number: "5511999999999", whatsapp_message: "Olá! Vim pela página da marca.", instagram_url: "https://instagram.com/", website_url: "https://plak.app", address: "Rua principal, 100 · Centro", maps_url: "https://maps.google.com", primary_color: "#17262D", secondary_color: "#D8EE77", background_color: "#F4F6F1", standard_button_color: "#FFFFFF", custom_button_color: "#D8EE77", seo_title: "", seo_description: "", seo_image_url: "", features: features("Serviço principal | Uma experiência pensada para você | A partir de R$ 80\nAtendimento especial | Fale com a nossa equipe | Consulte", "Marina | Atendimento impecável e muito rápido."), links: [{ label: "Agende ou peça pelo WhatsApp", url: "https://wa.me/5511999999999", kind: "whatsapp", color: "#17262D", position: 0 }, { label: "Veja nosso Instagram", url: "https://instagram.com/", kind: "site", color: "#FFFFFF", position: 1 }, { label: "Como chegar", url: "https://maps.google.com", kind: "maps", color: "#FFFFFF", position: 2 }], ...visual(category, index), ...values,
});
const preset = (id: string, name: string, category: TemplateCategory, description: string, tone: string, values: Partial<BusinessForm>, index: number): TemplatePreset => ({ id, name, category, description, tone, form: base(values, category, index) });

export const templatePresets: TemplatePreset[] = [
  preset("cafe-editorial", "Café Editorial", "Gastronomia", "Cardápio, reservas, foto de perfil e localização já configurados.", "#D7F878", { name: "Café Aurora", slug: "cafe-aurora", tagline: "Café bom, conversa melhor.", primary_color: "#263B35", secondary_color: "#D7F878", background_color: "#F5F1E8", features: features("Café coado | Grãos selecionados e preparo artesanal | R$ 9\nBolo do dia | Receita fresca toda manhã | R$ 14", "Ana | O melhor café do bairro.", "Especial da semana", "Café + bolo com condição especial até sexta.") }, 0),
  preset("restaurante-contemporaneo", "Restaurante Contemporâneo", "Gastronomia", "Página completa para reservas, menu, avaliações e mapa.", "#F2B84B", { name: "Casa Noma", slug: "casa-noma", tagline: "Sabores que ficam na memória.", primary_color: "#8A3D2E", secondary_color: "#F2B84B", background_color: "#FBF6EF", features: features("Menu executivo | Entrada, prato e sobremesa | R$ 59\nReserva de mesa | Garanta sua experiência | Consulte", "Rafael | Ambiente incrível e comida impecável.") }, 1),
  preset("bakery-soft", "Padaria Afetiva", "Gastronomia", "Visual acolhedor para mostrar produtos e receber pedidos.", "#E9A56B", { name: "Manhã & Trigo", slug: "manha-e-trigo", tagline: "Pão quente para dias melhores.", primary_color: "#9B5C3D", secondary_color: "#E9A56B", background_color: "#FFF8EE", features: features("Pão de fermentação natural | Assado todos os dias | R$ 18\nCesta de café | Para começar bem a manhã | R$ 42", "Lúcia | Tudo muito fresco e saboroso.") }, 2),
  preset("barber-dark", "Barbearia Dark", "Beleza", "Agenda, serviços, foto de perfil e contato em uma página forte.", "#D7F878", { name: "North Barber", slug: "north-barber", tagline: "Corte preciso. Estilo próprio.", primary_color: "#17262D", secondary_color: "#D7F878", background_color: "#F0F3EE", features: features("Corte clássico | Corte e finalização | R$ 80\nBarba completa | Toalha quente e acabamento | R$ 55", "João | Atendimento pontual e caprichado.") }, 0),
  preset("beauty-minimal", "Beauty Minimal", "Beleza", "Estética delicada para salão, nail designer e agendamento.", "#E8A9B8", { name: "Lume Beauty", slug: "lume-beauty", tagline: "Seu tempo de cuidado começa aqui.", primary_color: "#8D5667", secondary_color: "#E8A9B8", background_color: "#FFF7F5", features: features("Manicure premium | Esmaltação e cuidado completo | R$ 90\nDesign de sobrancelhas | Técnica personalizada | R$ 65", "Bia | Saí me sentindo maravilhosa.") }, 1),
  preset("studio-skin", "Clínica Glow", "Beleza", "Agendamento, localização e redes para uma clínica moderna.", "#B6D8C2", { name: "Glow Studio", slug: "glow-studio", tagline: "Pele saudável, beleza real.", primary_color: "#356A5D", secondary_color: "#B6D8C2", background_color: "#F1F8F3", features: features("Limpeza de pele | Avaliação e protocolo completo | R$ 150\nConsulta inicial | Plano personalizado de cuidados | Consulte", "Camila | Profissionais cuidadosas e atenciosas.") }, 2),
  preset("architect", "Arquiteto Portfolio", "Serviços", "Apresente projetos, portfólio, contato e posicionamento.", "#D7F878", { name: "Traço Norte", slug: "traco-norte", tagline: "Espaços com intenção.", primary_color: "#1F3439", secondary_color: "#D7F878", background_color: "#F4F5F1", features: features("Projeto residencial | Conceito, estudo e detalhamento | Sob consulta\nConsultoria expressa | Uma direção para seu espaço | R$ 450", "Pedro | Nosso projeto ganhou clareza e personalidade.") }, 0),
  preset("law-office", "Escritório Essencial", "Serviços", "Contato, credibilidade e serviços para profissionais.", "#C5A46D", { name: "Moraes & Lima", slug: "moraes-lima", tagline: "Clareza para decisões importantes.", primary_color: "#243A4A", secondary_color: "#C5A46D", background_color: "#F5F5F2", features: features("Consulta inicial | Entenda o seu caso com clareza | Consulte\nAtendimento empresarial | Soluções sob medida | Consulte", "Felipe | Comunicação clara do início ao fim.") }, 1),
  preset("consultant", "Consultoria Direct", "Serviços", "Captação de reuniões e apresentação profissional.", "#79B8C9", { name: "Núcleo Estratégia", slug: "nucleo-estrategia", tagline: "Ideias claras. Próximos passos.", primary_color: "#15566A", secondary_color: "#79B8C9", background_color: "#F1F7F8", features: features("Diagnóstico | Uma leitura objetiva do seu negócio | R$ 390\nMentoria | Próximos passos com acompanhamento | Consulte", "Juliana | Saí da conversa com um plano real.") }, 2),
  preset("real-estate", "Imobiliária Premium", "Serviços", "Link rápido para atendimento, imóveis e localização.", "#D5B46B", { name: "Casa Alta", slug: "casa-alta", tagline: "Encontre o lugar certo para viver.", primary_color: "#384B45", secondary_color: "#D5B46B", background_color: "#F6F3EC", features: features("Apartamento com varanda | 3 quartos · 2 vagas | R$ 890 mil\nAgende uma visita | Conheça seu próximo endereço | Consulte", "Marcos | Encontraram exatamente o que procurávamos.") }, 0),
  preset("local-shop", "Loja Local", "Varejo", "Coleção, atendimento e destaque de produto em uma página.", "#F39B72", { name: "Ponto & Forma", slug: "ponto-e-forma", tagline: "Peças escolhidas para o seu dia.", primary_color: "#9A4939", secondary_color: "#F39B72", background_color: "#FFF6F0", features: features("Peça destaque | Design autoral para todos os dias | R$ 189\nAtendimento personalizado | Encontre seu tamanho e estilo | Chame a gente", "Nina | A curadoria é linda e o atendimento também.") }, 1),
  preset("fashion-label", "Marca de Moda", "Varejo", "Página editorial para coleção, Instagram e loja online.", "#D7F878", { name: "Forma 01", slug: "forma-01", tagline: "Vista o que faz sentido.", primary_color: "#111A1D", secondary_color: "#D7F878", background_color: "#F2F3EE", features: features("Coleção 01 | Silhuetas essenciais e materiais naturais | Ver coleção\nPedido pelo WhatsApp | Atendimento personalizado | Chame a gente", "Bruna | A peça veste perfeitamente.") }, 2),
  preset("florist", "Floricultura Botânica", "Varejo", "Visual orgânico para pedidos, catálogo e mensagens.", "#A9D3A4", { name: "Verde Vivo", slug: "verde-vivo", tagline: "Flores para dizer sem palavras.", primary_color: "#356344", secondary_color: "#A9D3A4", background_color: "#F2F8F0", features: features("Buquê da semana | Flores da estação e folhagens | R$ 120\nArranjo personalizado | Criado para sua ocasião | Consulte", "Fernanda | O arranjo chegou perfeito.") }, 0),
  preset("pet-care", "Pet Care", "Serviços", "Banho, tosa e contato em um fluxo simples para tutores.", "#F7B45A", { name: "Patas & Companhia", slug: "patas-companhia", tagline: "Cuidado que eles sentem.", primary_color: "#A95D36", secondary_color: "#F7B45A", background_color: "#FFF8ED", features: features("Banho e tosa | Cuidado completo para seu pet | A partir de R$ 70\nTáxi pet | Buscamos e entregamos com segurança | Consulte", "Rita | Meu cachorro voltou feliz e cheiroso.") }, 1),
  preset("fitness", "Studio Fitness", "Serviços", "Aulas, horários e contato com energia visual.", "#C8E343", { name: "Pulse Studio", slug: "pulse-studio", tagline: "Movimente o seu melhor.", primary_color: "#17262D", secondary_color: "#C8E343", background_color: "#EEF3EC", features: features("Aula experimental | Conheça o studio sem compromisso | Grátis\nPlano mensal | Treinos e acompanhamento | Consulte", "Caio | A equipe me fez gostar de treinar.") }, 2),
  preset("photographer", "Fotógrafo Portfolio", "Criativo", "Portfólio visual com contato e redes em destaque.", "#D8C4FF", { name: "Mira Foto", slug: "mira-foto", tagline: "Histórias que merecem ficar.", primary_color: "#4C3B65", secondary_color: "#D8C4FF", background_color: "#F7F4FB", features: features("Ensaio de marca | Imagens que traduzem sua identidade | Consulte\nCasamento | Narrativa completa do seu dia | Consulte", "Lara | As fotos fizeram a gente reviver tudo.") }, 0),
  preset("music-artist", "Artista Musical", "Criativo", "Lançamentos, agenda e links essenciais para fãs.", "#F08BA8", { name: "Lia Nova", slug: "lia-nova", tagline: "Som para atravessar a noite.", primary_color: "#572943", secondary_color: "#F08BA8", background_color: "#FFF3F7", features: features("Novo single | Ouça agora em todas as plataformas | Ouvir\nShow ao vivo | Próxima apresentação | Ver agenda", "Beto | A música ficou na cabeça por dias.") }, 1),
  preset("event-planner", "Eventos & Festas", "Criativo", "Orçamentos, portfólio e contato para transformar ideias em eventos.", "#E8C875", { name: "Vértice Eventos", slug: "vertice-eventos", tagline: "Seu momento, do seu jeito.", primary_color: "#5C4A26", secondary_color: "#E8C875", background_color: "#FCF8EE", features: features("Planejamento completo | Do conceito à execução | Consulte\nDecoração personalizada | Um cenário com a sua cara | Consulte", "Aline | Tudo ficou mais bonito do que imaginávamos.") }, 2),
  preset("creator", "Creator Hub", "Criativo", "Central de links para conteúdo, comunidade e parcerias.", "#8BD5E8", { name: "Nexo Creator", slug: "nexo-creator", tagline: "Tudo o que eu crio, em um toque.", primary_color: "#15566A", secondary_color: "#8BD5E8", background_color: "#F0FAFC", features: features("Conteúdo novo | Veja o vídeo da semana | Assistir\nParcerias | Fale comigo para projetos | Enviar briefing", "Dani | Encontro tudo o que preciso aqui.") }, 0),
  preset("community", "Comunidade Local", "Criativo", "Conecte pessoas, agenda, redes e pontos de encontro.", "#D7F878", { name: "Bairro Vivo", slug: "bairro-vivo", tagline: "Mais perto de quem importa.", primary_color: "#315B4B", secondary_color: "#D7F878", background_color: "#F1F7EF", features: features("Próximo encontro | Sábado, às 10h | Ver agenda\nFaça parte | Receba novidades da comunidade | Inscrever", "Rosa | Finalmente um lugar para encontrar gente do bairro.") }, 1),
];
