import { useEffect, useState } from "react";
import { Check, ChevronLeft, LayoutPanelLeft, Palette, RotateCcw, Save, SlidersHorizontal, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { AdminShell } from "@/components/AdminShell";

type Preferences = { accent: string; sidebar: "narrow" | "normal" | "wide"; density: "compact" | "comfortable"; workspace: string; defaultGrid: boolean; defaultLeft: boolean; defaultRight: boolean };
const KEY = "plak-editor-preferences-v1";
const defaults: Preferences = { accent: "#8ca66b", sidebar: "normal", density: "comfortable", workspace: "#edf0e9", defaultGrid: true, defaultLeft: true, defaultRight: true };
function readPreferences(): Preferences { try { const raw = localStorage.getItem(KEY); return raw ? { ...defaults, ...JSON.parse(raw) } : defaults; } catch { return defaults; } }
function publishPreferences(value: Preferences) { localStorage.setItem(KEY, JSON.stringify(value)); window.dispatchEvent(new CustomEvent("plak-editor-preferences-changed", { detail: value })); }
const presets = [{ label: "Sálvia", value: "#8ca66b" }, { label: "Lima PLAK", value: "#c8e343" }, { label: "Azul", value: "#5b91d1" }, { label: "Violeta", value: "#8b70d6" }, { label: "Terracota", value: "#d47d5d" }, { label: "Rosa", value: "#d875a5" }];
export default function EditorPreferences() {
  const [prefs, setPrefs] = useState<Preferences>(readPreferences);
  const [saved, setSaved] = useState(true);
  useEffect(() => { publishPreferences(prefs); }, []);
  const update = (patch: Partial<Preferences>) => { const next = { ...prefs, ...patch }; setPrefs(next); setSaved(false); publishPreferences(next); };
  const save = () => { publishPreferences(prefs); setSaved(true); };
  const reset = () => { setPrefs(defaults); publishPreferences(defaults); setSaved(true); };
  return <AdminShell><div className="mx-auto max-w-5xl space-y-6">
    <header className="overflow-hidden rounded-[28px] bg-[#17262d] p-6 text-white shadow-lg sm:p-8"><Link href="/admin" className="mb-5 inline-flex items-center gap-2 text-xs font-bold text-white/70 hover:text-white"><ChevronLeft size={15}/> Voltar ao painel</Link><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#c8e343]">PREFERÊNCIAS DO STUDIO</p><h1 className="mt-2 font-display text-3xl font-black tracking-tight sm:text-4xl">Personalize seu editor.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-white/65">Ajuste a aparência e o espaço de trabalho para combinar com seu jeito de criar. Isso não altera os bio sites dos clientes.</p></div><div className="flex items-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-xs text-white/70"><Sparkles size={16} className="text-[#c8e343]"/> Prévia aplicada automaticamente</div></div></header>
    <div className="grid gap-5 lg:grid-cols-[1fr_320px]">
      <div className="space-y-5">
        <section className="rounded-[24px] border border-[#e0e5dc] bg-[#fffefa] p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf3e5] text-[#657f4d]"><Palette size={19}/></span><div><h2 className="font-display text-lg font-bold text-[#203439]">Cores do editor</h2><p className="text-xs text-[#829087]">Personalize a cor de destaque dos controles.</p></div></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{presets.map(p => <button key={p.value} onClick={() => update({ accent: p.value })} className={`flex min-h-12 items-center gap-2 rounded-xl border px-3 text-sm font-bold ${prefs.accent === p.value ? "border-[#243a35] bg-[#f2f5ed] text-[#203439]" : "border-[#e5e9e1] text-[#5f7069]"}`}><span className="h-5 w-5 rounded-full" style={{ background: p.value }}/>{p.label}{prefs.accent === p.value && <Check size={14} className="ml-auto"/>}</button>)}</div><label className="mt-4 flex items-center justify-between gap-3 rounded-xl bg-[#f6f7f2] p-3 text-sm font-semibold text-[#53645d]">Cor personalizada <span className="flex items-center gap-2"><input aria-label="Cor personalizada" type="color" value={prefs.accent} onChange={e => update({ accent: e.target.value })} className="h-9 w-12 cursor-pointer rounded border-0 bg-transparent"/><code className="text-xs">{prefs.accent}</code></span></label></section>
        <section className="rounded-[24px] border border-[#e0e5dc] bg-[#fffefa] p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf3e5] text-[#657f4d]"><LayoutPanelLeft size={19}/></span><div><h2 className="font-display text-lg font-bold text-[#203439]">Espaço de trabalho</h2><p className="text-xs text-[#829087]">Defina a largura dos painéis e o espaçamento.</p></div></div><div className="space-y-4"><div><p className="mb-2 text-xs font-bold uppercase tracking-wider text-[#849087]">Largura do painel lateral</p><div className="grid grid-cols-3 gap-2">{([ ["narrow","Estreito"], ["normal","Padrão"], ["wide","Amplo"] ] as const).map(([value,label]) => <button key={value} onClick={() => update({ sidebar: value })} className={`min-h-11 rounded-xl border text-sm font-bold ${prefs.sidebar === value ? "border-[#b5c79f] bg-[#edf3e5] text-[#435b39]" : "border-[#e3e8df] text-[#718078]"}`}>{label}</button>)}</div></div><div><p className="mb-2 text-xs font-bold uppercase tracking-wider text-[#849087]">Espaçamento da interface</p><div className="grid grid-cols-2 gap-2">{([ ["compact","Compacto"], ["comfortable","Confortável"] ] as const).map(([value,label]) => <button key={value} onClick={() => update({ density: value })} className={`min-h-11 rounded-xl border text-sm font-bold ${prefs.density === value ? "border-[#b5c79f] bg-[#edf3e5] text-[#435b39]" : "border-[#e3e8df] text-[#718078]"}`}>{label}</button>)}</div></div><label className="flex items-center justify-between gap-3 rounded-xl bg-[#f6f7f2] p-3 text-sm font-semibold text-[#53645d]">Fundo da área de trabalho<input type="color" aria-label="Fundo da área de trabalho" value={prefs.workspace} onChange={e => update({ workspace: e.target.value })} className="h-9 w-12 cursor-pointer rounded border-0 bg-transparent"/></label></div></section>
        <section className="rounded-[24px] border border-[#e0e5dc] bg-[#fffefa] p-5 sm:p-6"><div className="mb-4 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf3e5] text-[#657f4d]"><SlidersHorizontal size={19}/></span><div><h2 className="font-display text-lg font-bold text-[#203439]">Preferências ao abrir o editor</h2><p className="text-xs text-[#829087]">Escolha como o canvas começa.</p></div></div>{([["defaultGrid","Mostrar grade por padrão"],["defaultLeft","Abrir ferramentas à esquerda"],["defaultRight","Abrir propriedades à direita"]] as const).map(([key,label]) => <label key={key} className="flex min-h-12 cursor-pointer items-center justify-between gap-3 border-b border-[#eef0eb] py-2 last:border-0"><span className="text-sm font-medium text-[#53645d]">{label}</span><input type="checkbox" checked={prefs[key]} onChange={e => update({ [key]: e.target.checked } as Partial<Preferences>)} className="h-4 w-4 accent-[#718653]"/></label>)}</section>
        <div className="flex flex-wrap justify-between gap-3"><button onClick={reset} className="inline-flex min-h-11 items-center gap-2 rounded-full border border-[#dfe5dc] bg-white px-4 text-sm font-bold text-[#66766d]"><RotateCcw size={15}/> Restaurar padrão</button><button onClick={save} className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#17262d] px-5 text-sm font-bold text-white hover:bg-[#263d42]"><Save size={15}/>{saved ? "Preferências salvas" : "Salvar preferências"}</button></div>
      </div>
      <aside className="h-fit rounded-[24px] border border-[#e0e5dc] bg-[#fffefa] p-5"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#8b968d]">PRÉVIA</p><h3 className="mt-2 font-display text-lg font-bold text-[#203439]">Seu espaço de trabalho</h3><div className="mt-4 overflow-hidden rounded-2xl border border-[#dce2d9]" style={{ background: prefs.workspace }}><div className="flex h-10 items-center gap-2 bg-[#17262d] px-3"><span className="h-2 w-2 rounded-full bg-[#ef9b87]"/><span className="h-2 w-2 rounded-full bg-[#e6ce72]"/><span className="h-2 w-2 rounded-full bg-[#9bc68b]"/><span className="ml-auto h-4 w-16 rounded bg-white/10"/></div><div className="flex min-h-44"><div style={{ width: prefs.sidebar === "narrow" ? 38 : prefs.sidebar === "wide" ? 72 : 54 }} className="shrink-0 space-y-2 bg-white/80 p-2"><div className="h-5 rounded" style={{ background: prefs.accent }}/><div className="h-4 rounded bg-[#e7ebe2]"/><div className="h-4 rounded bg-[#e7ebe2]"/></div><div className="flex flex-1 items-center justify-center p-3"><div className="aspect-[4/3] w-full max-w-40 rounded-lg bg-white p-3 shadow-md"><div className="h-3 w-2/3 rounded" style={{ background: prefs.accent }}/><div className="mt-2 h-2 w-full rounded bg-[#e5e9e1]"/><div className="mt-1 h-2 w-4/5 rounded bg-[#e5e9e1]"/><div className="mt-3 h-6 rounded-lg" style={{ background: prefs.accent }}/></div></div></div></div><p className="mt-3 text-xs leading-5 text-[#849087]">As preferências são guardadas neste navegador. Elas afetam a interface do editor, não o conteúdo nem as cores dos sites dos clientes.</p></aside>
    </div>
  </div></AdminShell>;
}
