import { ArrowRight, ArrowUpRight, BadgeCheck, BarChart3, Check, ChevronRight, Clock3, Coffee, Layers3, LayoutTemplate, MapPin, MessageCircle, MousePointer2, Palette, QrCode, Rocket, ShoppingBag, Smartphone, Sparkles, Store, Utensils } from "lucide-react";
import { Link } from "wouter";
import { BrandLogo } from "@/components/BrandLogo";

const segments = [
  { icon: Utensils, title: "Restaurantes", text: "Cardápio, pedidos, reservas e localização." },
  { icon: ShoppingBag, title: "Lojas locais", text: "Produtos, catálogo e atendimento pelo WhatsApp." },
  { icon: Sparkles, title: "Beleza e bem-estar", text: "Serviços, agenda e contatos em poucos toques." },
  { icon: Store, title: "Negócios locais", text: "Uma página clara para apresentar seu negócio." },
];

export default function Home() {
  return <div className="min-h-screen overflow-hidden bg-[#f7f7f2] text-[#1c2a25]">
    <header className="relative z-20 mx-auto flex max-w-[1440px] items-center justify-between px-5 py-5 sm:px-10 lg:px-14">
      <BrandLogo />
      <nav className="hidden items-center gap-8 text-sm font-semibold text-[#657269] md:flex"><a href="#como-funciona" className="hover:text-[#263b30]">Como funciona</a><a href="#segmentos" className="hover:text-[#263b30]">Para negócios</a><a href="#vantagens" className="hover:text-[#263b30]">Vantagens</a><Link href="/login" className="rounded-full border border-[#dce3d8] px-5 py-2.5 text-[#263b30] transition hover:border-[#263b30]">Entrar <ArrowRight className="ml-2 inline h-4 w-4" /></Link></nav>
      <Link href="/login" className="inline-flex items-center gap-2 rounded-full bg-[#263b30] px-4 py-2.5 text-xs font-extrabold text-white md:hidden">Acessar <ArrowUpRight size={15}/></Link>
    </header>

    <main>
      <section className="relative px-5 pb-20 pt-10 sm:px-10 sm:pb-28 sm:pt-16 lg:px-14 lg:pt-20">
        <div className="pointer-events-none absolute -right-40 top-0 h-[620px] w-[620px] rounded-full bg-[#e6edce] blur-3xl" />
        <div className="relative mx-auto grid max-w-[1320px] items-center gap-14 lg:grid-cols-[.92fr_1.08fr]">
          <div className="relative z-10 max-w-[620px]">
            <div className="inline-flex items-center gap-2 rounded-full border border-[#dce5d2] bg-white/75 px-3.5 py-2 text-[11px] font-extrabold uppercase tracking-[.13em] text-[#63764b]"><span className="h-2 w-2 rounded-full bg-[#9bb66d]"/> Presença digital para negócios reais</div>
            <h1 className="mt-7 text-[clamp(3.5rem,7.4vw,6.8rem)] font-black leading-[.91] tracking-[-.085em]">Seu negócio<br/>merece estar<br/><span className="text-[#778b53]">bem apresentado.</span></h1>
            <p className="mt-7 max-w-[490px] text-base leading-8 text-[#68756d] sm:text-lg">Bio sites profissionais para lojas, restaurantes e negócios locais. Tudo importante em uma página bonita, rápida e fácil de compartilhar.</p>
            <div className="mt-8 flex flex-wrap gap-3"><Link href="/login" className="inline-flex min-h-14 items-center rounded-full bg-[#263b30] px-7 text-sm font-extrabold text-white shadow-[0_12px_28px_rgba(38,59,48,.17)] transition hover:-translate-y-0.5 hover:bg-[#354d3e]">Criar meu bio site <ArrowUpRight className="ml-3 h-4 w-4"/></Link><a href="#como-funciona" className="inline-flex min-h-14 items-center rounded-full border border-[#d9e0d6] bg-white/70 px-6 text-sm font-bold text-[#4d5f53] hover:bg-white">Conhecer a plataforma</a></div>
            <div className="mt-9 flex flex-wrap gap-x-5 gap-y-3 text-xs font-semibold text-[#748177]"><span><Check className="mr-1.5 inline h-4 w-4 text-[#78934e]"/>Pensado para celular</span><span><Check className="mr-1.5 inline h-4 w-4 text-[#78934e]"/>WhatsApp e redes sociais</span><span><Check className="mr-1.5 inline h-4 w-4 text-[#78934e]"/>Link fácil de compartilhar</span></div>
          </div>
          <div className="relative mx-auto w-full max-w-[640px] pb-7 pt-3">
            <div className="absolute inset-x-[10%] top-[10%] h-[78%] rounded-[50%] bg-[#dfe8cd] blur-2xl" />
            <div className="relative grid grid-cols-[.75fr_1fr] items-center gap-3 sm:gap-5">
              <div className="relative z-10 -mr-8 mt-16 rounded-[24px] border border-white/80 bg-white/90 p-4 shadow-[0_25px_65px_rgba(42,61,45,.12)] backdrop-blur sm:-mr-12 sm:rounded-[28px] sm:p-5">
                <div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#edf2e5] text-[#647b4b]"><BarChart3 size={17}/></span><span className="text-[10px] font-extrabold uppercase tracking-wider text-[#7b887b]">Visão geral</span></div>
                <p className="mt-5 text-2xl font-black tracking-tight sm:text-3xl">Seu negócio</p><p className="mt-1 text-xs text-[#849087]">Presente onde seu cliente está.</p>
                <div className="mt-5 space-y-2"><div className="flex items-center gap-2 rounded-xl bg-[#f2f5ed] p-2.5 text-xs font-bold"><MessageCircle size={15} className="text-[#67864b]"/> WhatsApp <ChevronRight size={14} className="ml-auto text-[#a4afa0]"/></div><div className="flex items-center gap-2 rounded-xl bg-[#f2f5ed] p-2.5 text-xs font-bold"><MapPin size={15} className="text-[#67864b]"/> Como chegar <ChevronRight size={14} className="ml-auto text-[#a4afa0]"/></div></div>
              </div>
              <div className="relative rounded-[34px] border-[7px] border-[#27372e] bg-[#27372e] p-1.5 shadow-[0_35px_85px_rgba(35,54,41,.28)] sm:rounded-[42px] sm:border-[9px] sm:p-2"><div className="absolute left-1/2 top-2 z-10 h-5 w-20 -translate-x-1/2 rounded-full bg-[#17231c] sm:top-3 sm:h-6 sm:w-24"/><div className="min-h-[450px] overflow-hidden rounded-[27px] bg-[#faf8f1] px-4 pb-5 pt-10 sm:min-h-[560px] sm:rounded-[32px] sm:px-6 sm:pt-12">
                <div className="flex items-center justify-between text-[9px] font-bold text-[#8c9689]"><span>PLAK BIO SITE</span><span className="flex items-center gap-1"><span className="h-1.5 w-1.5 rounded-full bg-[#87a65e]"/> ONLINE</span></div>
                <div className="mt-7 overflow-hidden rounded-[22px] bg-[#d9dfca] sm:rounded-[28px]"><img src="/template-references/bajor-reference.png" alt="Exemplo de identidade visual para negócio local" className="h-32 w-full object-cover sm:h-40"/></div>
                <div className="relative -mt-8 flex flex-col items-center text-center"><img src="/template-references/business-card-reference.webp" alt="Identidade de marca de exemplo" className="h-[68px] w-[68px] rounded-2xl border-4 border-[#faf8f1] bg-white object-cover sm:h-20 sm:w-20"/><h2 className="mt-3 text-2xl font-black tracking-[-.06em] sm:text-3xl">Casa & Grão</h2><p className="mt-1 text-xs text-[#7b877b]">Café, comida e bons encontros.</p></div>
                <div className="mt-5 space-y-2"><div className="flex items-center gap-3 rounded-2xl bg-[#293e32] p-3.5 text-white"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#d9e8bd] text-[#293e32]"><MessageCircle size={17}/></span><span className="flex-1 text-left"><b className="block text-xs">Peça pelo WhatsApp</b><small className="text-[10px] text-white/55">Estamos esperando você</small></span><ArrowUpRight size={15}/></div><div className="flex items-center gap-3 rounded-2xl border border-[#e5e8dd] bg-white p-3.5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#f0f2e9] text-[#71865b]"><Coffee size={17}/></span><span className="flex-1 text-left"><b className="block text-xs">Conheça nosso cardápio</b><small className="text-[10px] text-[#89948a]">Feito com cuidado todos os dias</small></span><ChevronRight size={15} className="text-[#a1aaa0]"/></div><div className="flex items-center gap-3 rounded-2xl border border-[#e5e8dd] bg-white p-3.5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#f0f2e9] text-[#71865b]"><MapPin size={17}/></span><span className="flex-1 text-left"><b className="block text-xs">Visite a nossa loja</b><small className="text-[10px] text-[#89948a]">Como chegar</small></span><ChevronRight size={15} className="text-[#a1aaa0]"/></div></div>
                <div className="mt-5 flex items-center justify-center gap-2 text-[9px] font-bold uppercase tracking-[.14em] text-[#9ba397]"><QrCode size={13}/> Um link. Tudo conectado.</div>
              </div></div>
            </div>
            <div className="absolute -bottom-1 right-[1%] hidden items-center gap-3 rounded-2xl border border-white bg-white/95 px-4 py-3 shadow-xl sm:flex"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eaf1de] text-[#657c4b]"><MousePointer2 size={18}/></span><span><b className="block text-xs">Feito para converter</b><small className="text-[10px] text-[#849087]">Contato a poucos toques</small></span></div>
          </div>
        </div>
      </section>

      <section id="como-funciona" className="border-y border-[#e5e9df] bg-white px-5 py-16 sm:px-10 sm:py-20 lg:px-14"><div className="mx-auto max-w-[1240px]"><div className="max-w-2xl"><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#7b9258]">Simples do início à entrega</p><h2 className="mt-4 text-4xl font-black leading-[.98] tracking-[-.07em] sm:text-5xl">Da ideia ao link pronto,<br/>sem complicar.</h2><p className="mt-4 text-sm leading-7 text-[#758178]">Uma experiência prática para colocar as informações mais importantes do seu negócio em um só lugar.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[{n:"01",icon:LayoutTemplate,title:"Escolha uma base",text:"Comece com um modelo pensado para o seu segmento ou crie uma página do zero."},{n:"02",icon:Palette,title:"Personalize",text:"Ajuste textos, fotos, cores e botões para combinar com a identidade da sua marca."},{n:"03",icon:Rocket,title:"Publique e compartilhe",text:"Receba um link pronto para usar na bio das redes, no WhatsApp, no QR Code ou no NFC."}].map(item=><article key={item.n} className="rounded-[24px] border border-[#e6eade] bg-[#fafbf7] p-6 sm:p-7"><div className="flex items-center justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#eaf0df] text-[#637b49]"><item.icon size={21}/></span><span className="text-xs font-black tracking-widest text-[#b0b9a8]">{item.n}</span></div><h3 className="mt-6 text-xl font-black tracking-tight">{item.title}</h3><p className="mt-3 text-sm leading-6 text-[#78847a]">{item.text}</p></article>)}</div></div></section>

      <section id="segmentos" className="px-5 py-16 sm:px-10 sm:py-20 lg:px-14"><div className="mx-auto max-w-[1240px]"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#7b9258]">Feito para o dia a dia</p><h2 className="mt-4 text-4xl font-black tracking-[-.07em] sm:text-5xl">O essencial do seu<br/>negócio, bem apresentado.</h2></div><p className="max-w-sm text-sm leading-7 text-[#758178]">Cada negócio tem necessidades diferentes. Monte uma página com os recursos que fazem sentido para você.</p></div><div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{segments.map(({icon:Icon,title,text})=><article key={title} className="rounded-[22px] border border-[#e0e6db] bg-white p-5 transition hover:-translate-y-1 hover:shadow-[0_15px_35px_rgba(38,59,48,.07)]"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#eff3e8] text-[#6c8253]"><Icon size={19}/></span><h3 className="mt-5 font-extrabold">{title}</h3><p className="mt-2 text-xs leading-6 text-[#7c887e]">{text}</p></article>)}</div></div></section>

      <section id="vantagens" className="px-5 pb-20 sm:px-10 sm:pb-24 lg:px-14"><div className="relative mx-auto max-w-[1240px] overflow-hidden rounded-[30px] bg-[#263b30] px-6 py-10 text-white sm:px-10 sm:py-14 lg:px-14"><div className="pointer-events-none absolute -right-20 -top-32 h-96 w-96 rounded-full border-[48px] border-white/[.045]"/><div className="relative grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#d4e6b7]">Presença digital, sem complicação</p><h2 className="mt-4 max-w-2xl text-4xl font-black leading-[.98] tracking-[-.07em] sm:text-5xl">Tudo o que seu cliente procura.<br/><span className="text-[#c7dda6]">Em um só lugar.</span></h2><p className="mt-5 max-w-xl text-sm leading-7 text-white/65">Organize seu contato, seus canais e as informações do negócio em uma página fácil de acessar e compartilhar.</p><Link href="/login" className="mt-7 inline-flex min-h-12 items-center rounded-full bg-[#d7e9b8] px-6 text-sm font-black text-[#263b30] transition hover:-translate-y-0.5">Começar agora <ArrowUpRight className="ml-3 h-4 w-4"/></Link></div><div className="grid gap-3 sm:grid-cols-2">{[{icon:Smartphone,title:"Responsivo",text:"Experiência pensada para telas pequenas."},{icon:Clock3,title:"Prático",text:"Informações importantes sem procurar demais."},{icon:BadgeCheck,title:"Sua identidade",text:"Cores e imagens alinhadas à sua marca."},{icon:Layers3,title:"Tudo organizado",text:"Contato, redes, cardápio e localização."}].map(({icon:Icon,title,text})=><div key={title} className="rounded-2xl border border-white/10 bg-white/[.06] p-4"><Icon size={19} className="text-[#d7e9b8]"/><b className="mt-4 block text-sm">{title}</b><p className="mt-1 text-xs leading-5 text-white/50">{text}</p></div>)}</div></div></div></section>
    </main>
    <footer className="border-t border-[#e3e8df] px-5 py-7 sm:px-10 lg:px-14"><div className="mx-auto flex max-w-[1240px] flex-col justify-between gap-4 sm:flex-row sm:items-center"><BrandLogo compact/><p className="text-xs text-[#8a958b]">PLAK Studio · Presença digital para negócios locais.</p><Link href="/login" className="text-xs font-extrabold text-[#52684a]">Acessar plataforma <ArrowRight className="ml-1 inline h-3.5 w-3.5"/></Link></div></footer>
  </div>;
}
