import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Check, ChevronLeft, ChevronRight, Eye, ImagePlus, Link2, Loader2, Monitor, Palette, Plus, Save, Smartphone, Trash2, Type, Upload, Undo2, Redo2, X, Layers, Settings2 } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";
import { AdminShell } from "@/components/AdminShell";
import "./ClientEditor.css";
import { getBusiness, saveBusiness, uploadAsset } from "@/lib/data";
import type { BusinessForm, BusinessMedia, LinkKind } from "@/lib/types";
import { normalizeBusinessForm, normalizeInstagram, normalizeSlug, validateBusinessForm, validateFile } from "@/lib/validation";

const defaultLayout = { section_order: ["actions", "campaign", "catalog", "testimonials", "lead", "gallery", "address"], hidden_sections: [] as string[], cover_enabled: true, profile_position: "cover" as const, profile_shape: "circle" as const, text_align: "center" as const, button_style: "soft" as const, show_gallery: true, cover_treatment: "light" as const, logo_size: "medium" as const, logo_shape: "circle" as const, logo_fit: "contain" as const, cover_opacity: 55, cover_position_x: 50, cover_position_y: 50, logo_offset_x: 0, logo_offset_y: 0, logo_scale: 1, cover_scale: 100, title_color: "#0f172a", tagline_color: "#64748b", font_family: "Inter", title_font_size: 30, tagline_font_size: 14, section_spacing: "comfortable" as const, page_style: "clean" as const, background_effect: "solid" as const, hero_layout: "classic" as const, button_size: "medium" as const, button_shadow: true, button_text_color: "#263b3a", custom_button_text_color: "#FFFFFF", card_style: "soft" as const, gallery_layout: "floating" as const, gallery_radius: 22, gallery_gap: 12, gallery_background: "transparent", section_title_color: "#253d3e", body_text_color: "#718078", accent_color: "#91a08f", background_overlay: 55 };
const empty: BusinessForm = { name: "", slug: "", logo_url: "", tagline: "Olá! Como podemos ajudar?", google_review_url: "", whatsapp_number: "", whatsapp_message: "", instagram_url: "", website_url: "", address: "", maps_url: "", primary_color: "#66754B", secondary_color: "#C6B887", background_color: "#F5F4EC", background_image_url: "", standard_button_color: "#FFFFFF", custom_button_color: "#66754B", seo_title: "", seo_description: "", seo_image_url: "", features: { layout: defaultLayout, lead_enabled: false, lead_title: "Fale com a gente", lead_button: "Enviar mensagem", campaign_enabled: false, campaign_title: "", campaign_text: "", campaign_cta: "Saiba mais", campaign_url: "", catalog_text: "", catalog_title: "Produtos e serviços", catalog_subtitle: "Veja nossas principais opções", testimonials_text: "", testimonials_title: "O que nossos clientes dizem", qr_label: "PLAK", show_badge: true, catalog_items: [] }, links: [], media: [] };
type Tool = "select" | "text" | "image" | "buttons" | "style" | "page";
type Target = "page" | "cover" | "identity" | "tagline" | "actions" | "gallery" | "catalog" | "campaign" | "testimonials" | "contact";
const fieldClass = "w-full rounded-xl border border-[#dfe5d9] bg-white px-3 py-2.5 text-sm text-[#26372c] outline-none transition focus:border-[#7d915c] focus:ring-4 focus:ring-[#d8ee77]/35";

export default function ClientEditor() {
  const [, params] = useRoute("/admin/client/:id");
  const [, navigate] = useLocation();
  const editing = Boolean(params?.id);
  const [form, setForm] = useState<BusinessForm>(empty);
  const [loading, setLoading] = useState(editing);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [id, setId] = useState<string | undefined>(params?.id);
  const [tool, setTool] = useState<Tool>("select");
  const [target, setTarget] = useState<Target>("identity");
  const [leftOpen, setLeftOpen] = useState(true);
  const [rightOpen, setRightOpen] = useState(false);
  const [mobile, setMobile] = useState(false);
  const [history, setHistory] = useState<BusinessForm[]>([]);
  const [future, setFuture] = useState<BusinessForm[]>([]);
  const [logoFile, setLogoFile] = useState<File | null>(null);
  const [coverFile, setCoverFile] = useState<File | null>(null);
  const [mediaFiles, setMediaFiles] = useState<File[]>([]);
  const logoRef = useRef<HTMLInputElement>(null);
  const coverRef = useRef<HTMLInputElement>(null);
  const mediaRef = useRef<HTMLInputElement>(null);
  const layout = { ...defaultLayout, ...(form.features.layout || {}) };
  const catalog = form.features.catalog_items || [];
  const visibleLinks = useMemo(() => {
    const auto = [
      form.whatsapp_number ? { label: "Falar no WhatsApp", url: `https://wa.me/${form.whatsapp_number.replace(/\D/g, "")}${form.whatsapp_message ? `?text=${encodeURIComponent(form.whatsapp_message)}` : ""}`, kind: "whatsapp" as LinkKind, color: form.custom_button_color, position: 0 } : null,
      form.instagram_url ? { label: "Instagram", url: form.instagram_url, kind: "other" as LinkKind, color: form.custom_button_color, position: 1 } : null,
      form.google_review_url ? { label: "Avaliar no Google", url: form.google_review_url, kind: "other" as LinkKind, color: form.custom_button_color, position: 2 } : null,
      form.website_url ? { label: "Visitar site", url: form.website_url, kind: "site" as LinkKind, color: form.custom_button_color, position: 3 } : null,
    ].filter(Boolean) as {label:string;url:string;kind:LinkKind;color:string;position:number}[];
    return [...auto, ...form.links].filter(x => x.label.trim());
  }, [form]);

  useEffect(() => {
    if (!params?.id) { setLoading(false); return; }
    getBusiness(params.id).then(b => setForm({ ...empty, ...b, google_review_url: b.google_review_url || "", whatsapp_number: b.whatsapp_number || "", whatsapp_message: b.whatsapp_message || "", instagram_url: b.instagram_url || "", website_url: b.website_url || "", address: b.address || "", maps_url: b.maps_url || "", seo_title: b.seo_title || "", seo_description: b.seo_description || "", seo_image_url: b.seo_image_url || "", logo_url: b.logo_url || "", background_image_url: b.background_image_url || "", features: { ...empty.features, ...(b.features || {}), layout: { ...defaultLayout, ...(b.features?.layout || {}) }, catalog_items: b.features?.catalog_items || [] }, links: b.business_links || [], media: b.business_media || [] })).then(() => setId(params.id)).catch(e => setError(e.message || "Não foi possível abrir o cliente.")).finally(() => setLoading(false));
  }, [params?.id]);

  const change = (updater: (current: BusinessForm) => BusinessForm) => {
    setForm(current => { const next = updater(current); setHistory(h => [...h.slice(-39), JSON.parse(JSON.stringify(current))]); setFuture([]); setNotice(""); return next; });
  };
  const update = (key: keyof BusinessForm, value: any) => change(c => ({ ...c, [key]: value }));
  const updateName = (value: string) => change(c => ({ ...c, name: value, slug: !c.slug || c.slug === normalizeSlug(c.name) ? normalizeSlug(value) : c.slug }));
  const updateLayout = (patch: Record<string, any>) => change(c => ({ ...c, features: { ...c.features, layout: { ...defaultLayout, ...(c.features.layout || {}), ...patch } } }));
  const updateFeatures = (patch: Record<string, any>) => change(c => ({ ...c, features: { ...c.features, ...patch } }));
  const undo = () => { if (!history.length) return; setFuture(f => [JSON.parse(JSON.stringify(form)), ...f]); setForm(history[history.length - 1]); setHistory(h => h.slice(0, -1)); };
  const redo = () => { if (!future.length) return; setHistory(h => [...h, JSON.parse(JSON.stringify(form))]); setForm(future[0]); setFuture(f => f.slice(1)); };
  const addButton = () => change(c => ({ ...c, links: [...c.links, { label: "Novo botão", url: "https://", kind: "site" as LinkKind, color: c.custom_button_color || c.primary_color, position: c.links.length }] }));
  const addMedia = (file: File) => { const issue = validateFile(file, file.type.startsWith("video/") ? "video" : "media"); if (issue) { setError(issue); return; } setMediaFiles(f => [...f, file]); change(c => ({ ...c, media: [...c.media, { type: file.type.startsWith("video/") ? "video" : "image", url: URL.createObjectURL(file), alt: "Imagem da página", position: c.media.length, file, object_position_x: 50, object_position_y: 50, object_scale: 1 }] })); };

  const save = async (preview = false) => {
    setError(""); setNotice("");
    const normalized = normalizeBusinessForm({ ...form, slug: form.slug || form.name });
    const errors = validateBusinessForm(normalized);
    if (Object.keys(errors).length) { setError(Object.values(errors)[0]); return; }
    setSaving(true);
    try {
      const cleanMedia = normalized.media.filter(m => !m.file && !m.url.startsWith("blob:")).map(({file, ...m}) => m);
      const clean: BusinessForm = { ...normalized, logo_url: logoFile ? "" : normalized.logo_url, background_image_url: coverFile ? "" : normalized.background_image_url, media: cleanMedia, features: { ...normalized.features, catalog_items: (normalized.features.catalog_items || []).map(({file, ...x}) => x), blocks: (normalized.features.blocks || []).map(({file, ...x}) => x) } };
      const first = await saveBusiness(clean, id);
      let logoUrl = clean.logo_url, backgroundUrl = clean.background_image_url;
      if (logoFile) logoUrl = (await uploadAsset(logoFile, first.id, "logo")).url;
      if (coverFile) backgroundUrl = (await uploadAsset(coverFile, first.id, "background")).url;
      const uploaded: BusinessMedia[] = [];
      for (const item of normalized.media) {
        if (item.file) { const asset = await uploadAsset(item.file, first.id, "media"); uploaded.push({ ...item, url: asset.url, storage_path: asset.path, file: undefined }); }
        else if (!item.url.startsWith("blob:")) uploaded.push({ ...item, file: undefined });
      }
      const final = await saveBusiness({ ...normalized, logo_url: logoUrl, background_image_url: backgroundUrl, media: uploaded, features: { ...normalized.features, catalog_items: (normalized.features.catalog_items || []).map(({file, ...x}) => x), blocks: (normalized.features.blocks || []).map(({file, ...x}) => x) } }, first.id);
      setId(final.id); setForm(c => ({ ...c, logo_url: logoUrl, background_image_url: backgroundUrl, media: uploaded })); setLogoFile(null); setCoverFile(null); setMediaFiles([]); setHistory([]); setFuture([]); setNotice("Alterações salvas com sucesso.");
      if (preview) window.open(`/${final.slug}`, "_blank", "noopener,noreferrer");
    } catch (e: any) { setError(e.message || "Não foi possível salvar a página."); }
    finally { setSaving(false); }
  };

  const pickTarget = (next: Target) => { setTarget(next); setRightOpen(true); };
  const editable = (value: string, onChange: (v: string) => void, className: string, style?: React.CSSProperties) => <span contentEditable suppressContentEditableWarning spellCheck={false} onClick={e => { e.stopPropagation(); }} onInput={e => onChange(e.currentTarget.textContent || "")} className={`${className} outline-none`} style={style}>{value}</span>;
  const buttonStyle: React.CSSProperties = { background: form.custom_button_color || form.primary_color, color: layout.custom_button_text_color || "#fff", borderRadius: layout.button_style === "pill" ? 999 : layout.button_style === "square" ? 8 : 16 };

  if (loading) return <AdminShell><div className="grid min-h-[60vh] place-items-center text-[#687764]"><Loader2 className="animate-spin"/> Carregando editor...</div></AdminShell>;

  return <AdminShell><div className="plak-new-editor" style={{ height: "calc(100dvh - 92px)" }}>
    <header className="plak-editor-topbar">
      <div className="flex min-w-0 items-center gap-3"><Link href="/admin" className="plak-icon-btn" aria-label="Voltar"><ArrowLeft size={18}/></Link><div className="min-w-0"><div className="flex items-center gap-2"><span className="plak-brand-dot"/><strong className="text-sm tracking-tight">PLAK <span className="font-normal text-[#8a9485]">/ Editor de página</span></strong></div><div className="truncate text-xs text-[#8a9485]">{form.name || "Página sem título"} <span className="mx-1">·</span> {id ? "Rascunho editável" : "Novo projeto"}</div></div></div>
      <div className="flex items-center gap-1.5"><button className="plak-icon-btn" onClick={undo} disabled={!history.length} title="Desfazer"><Undo2 size={17}/></button><button className="plak-icon-btn" onClick={redo} disabled={!future.length} title="Refazer"><Redo2 size={17}/></button><span className="mx-1 hidden h-6 w-px bg-[#e5e9df] sm:block"/><button className="plak-secondary-btn" onClick={() => save(true)} disabled={saving}><Eye size={16}/> <span className="hidden sm:inline">Visualizar</span></button><button className="plak-save-btn" onClick={() => save(false)} disabled={saving}>{saving ? <Loader2 size={16} className="animate-spin"/> : <Save size={16}/>}<span>{saving ? "Salvando" : "Salvar"}</span></button></div>
    </header>
    {(error || notice) && <div className={`mx-3 mt-2 rounded-xl px-4 py-2 text-sm ${error ? "bg-red-50 text-red-700" : "bg-[#eef5dc] text-[#52683a]"}`}>{error || notice}<button className="float-right" onClick={() => {setError("");setNotice("")}}><X size={15}/></button></div>}
    <div className={`plak-editor-workspace ${!leftOpen ? "left-collapsed" : ""} ${!rightOpen ? "right-collapsed" : ""}`}>
      {leftOpen && <aside className="plak-tool-rail"><div className="plak-rail-label">CRIAR</div>{([ ["select",Layers,"Selecionar"],["text",Type,"Texto"],["image",ImagePlus,"Imagens"],["buttons",Link2,"Botões"],["style",Palette,"Estilo"],["page",Settings2,"Página"]] as const).map(([key,Icon,label])=><button key={key} className={`plak-tool ${tool===key?"active":""}`} onClick={() => {setTool(key);setRightOpen(true); if(key==="text")pickTarget("identity"); if(key==="image")pickTarget("gallery"); if(key==="buttons")pickTarget("actions"); if(key==="style")pickTarget("page"); if(key==="page")pickTarget("contact");}}><Icon size={19}/><span>{label}</span></button>)}<div className="mt-auto pt-4"><button className="plak-tool" onClick={() => setLeftOpen(false)} title="Recolher ferramentas"><ChevronLeft size={18}/><span>Recolher</span></button></div></aside>}
      {!leftOpen && <button className="plak-edge-toggle left-edge" onClick={() => setLeftOpen(true)} title="Abrir ferramentas"><ChevronRight size={17}/></button>}
      <main className="plak-canvas-area"><div className="plak-canvas-toolbar"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#a8c66c]"/><span>Monte sua página</span><span className="plak-live-pill">CLIQUE E EDITE</span></div><div className="flex items-center gap-1"><button className={`plak-view-btn ${!mobile?"selected":""}`} onClick={() => setMobile(false)} title="Visualização ampla"><Monitor size={15}/></button><button className={`plak-view-btn ${mobile?"selected":""}`} onClick={() => setMobile(true)} title="Visualização móvel"><Smartphone size={15}/></button></div></div>
        <div className="plak-canvas-scroll"><div className={`plak-page-frame ${mobile?"mobile-preview":""}`} style={{ background: form.background_image_url ? `linear-gradient(#ffffff22,#ffffff22),url(${form.background_image_url}) center/cover` : form.background_color, fontFamily: layout.font_family }}>
          <div className={`plak-cover-area ${target==="cover"?"is-selected":""}`} onClick={() => pickTarget("cover")} style={{ backgroundImage: form.background_image_url ? `linear-gradient(${layout.cover_treatment === "dark" ? "#10201788" : "#ffffff44"},${layout.cover_treatment === "dark" ? "#10201788" : "#ffffff44"}),url(${form.background_image_url})` : `linear-gradient(135deg, ${form.primary_color}22, ${form.secondary_color}66)` }}><button className="plak-cover-edit" onClick={e => {e.stopPropagation();coverRef.current?.click()}}><ImagePlus size={14}/> Alterar capa</button><div className="plak-profile" onClick={e => {e.stopPropagation();pickTarget("identity")}}>{form.logo_url ? <img src={form.logo_url} alt="Logo"/> : <span>{form.name?.slice(0,1).toUpperCase() || "P"}</span>}<button onClick={e=>{e.stopPropagation();logoRef.current?.click()}} title="Trocar logo"><Upload size={13}/></button></div></div>
          <div className={`plak-page-content ${target==="identity"?"is-selected":""}`} onClick={() => pickTarget("identity")} style={{ textAlign: layout.text_align as any }}>
            {editable(form.name || "Nome da sua marca", updateName, "plak-edit-title", {color:layout.title_color || form.primary_color, fontSize:layout.title_font_size || 30})}
            <div className="mt-2">{editable(form.tagline || "Escreva uma frase que apresente sua marca", v=>update("tagline",v), "plak-edit-tagline", {color:layout.tagline_color || "#64748b", fontSize:layout.tagline_font_size || 14})}</div>
          </div>
          <div className={`plak-page-section ${target==="actions"?"is-selected":""}`} onClick={() => pickTarget("actions")}><div className="plak-section-chip">Botões e links</div>{visibleLinks.length ? visibleLinks.map((link,i)=>{const autoCount=[form.whatsapp_number,form.instagram_url,form.google_review_url,form.website_url].filter(Boolean).length;const customIndex=i-autoCount;return <div key={`${link.label}-${i}`} className="plak-preview-link" onClick={e=>{e.stopPropagation();pickTarget("actions")}} style={i===0?buttonStyle:{background:form.standard_button_color,color:layout.button_text_color || "#314236",borderRadius:layout.button_style==="pill"?999:16}}><span>{customIndex>=0 ? editable(link.label || "Novo botão",v=>change(c=>({...c,links:c.links.map((x,j)=>j===customIndex?{...x,label:v}:x)})),"plak-inline-button") : link.label}</span><span>↗</span></div>}) : <button className="plak-add-placeholder" onClick={e=>{e.stopPropagation();addButton();pickTarget("actions")}}><Plus size={16}/> Adicionar botão de contato</button>}</div>
          {form.features.campaign_enabled && <div className={`plak-preview-card ${target==="campaign"?"is-selected":""}`} onClick={()=>pickTarget("campaign")}><span className="text-[10px] font-bold uppercase tracking-widest opacity-60">Destaque</span><h3>{editable(form.features.campaign_title || "Uma novidade", v=>updateFeatures({campaign_title:v}), "plak-inline-heading")}</h3><p>{editable(form.features.campaign_text || "Adicione os detalhes da sua campanha.", v=>updateFeatures({campaign_text:v}), "plak-inline-paragraph")}</p></div>}
          {catalog.length>0 && <div className={`plak-preview-card ${target==="catalog"?"is-selected":""}`} onClick={()=>pickTarget("catalog")}><h3>{editable(form.features.catalog_title || "Produtos e serviços", v=>updateFeatures({catalog_title:v}), "plak-inline-heading")}</h3><p className="mb-3 text-xs text-[#778477]">{editable(form.features.catalog_subtitle || "Veja nossas principais opções", v=>updateFeatures({catalog_subtitle:v}), "plak-inline-paragraph")}</p><div className="grid grid-cols-2 gap-3">{catalog.slice(0,4).map((item,i)=><div key={item.id} className="overflow-hidden rounded-xl bg-white text-left"><div className="h-24 bg-[#e9ede4]">{item.image_url&&<img src={item.image_url} className="h-full w-full object-cover"/>}</div><div className="p-2"><div className="text-xs font-bold">{editable(item.title || "Nome do produto", v=>updateFeatures({catalog_items:catalog.map((x,j)=>j===i?{...x,title:v}:x)}), "plak-inline-product")}</div><div className="mt-1 text-xs" style={{color:form.primary_color}}>{item.price}</div></div></div>)}</div></div>}
          {(form.features.testimonials_text || target==="testimonials") && <div className={`plak-preview-card ${target==="testimonials"?"is-selected":""}`} onClick={()=>pickTarget("testimonials")}><h3>{editable(form.features.testimonials_title || "O que nossos clientes dizem", v=>updateFeatures({testimonials_title:v}), "plak-inline-heading")}</h3><p className="mt-2 text-sm italic">“{editable((form.features.testimonials_text || "Escreva aqui um depoimento de cliente").split("\n")[0], v=>updateFeatures({testimonials_text:v}), "plak-inline-paragraph") }”</p><div className="mt-2 text-amber-500">★★★★★</div></div>}
          {form.media.length>0 && <div className={`plak-preview-card ${target==="gallery"?"is-selected":""}`} onClick={()=>pickTarget("gallery")}><h3>Galeria</h3><div className="mt-3 grid grid-cols-2 gap-2">{form.media.slice(0,6).map((m,i)=><div key={`${m.url}-${i}`} className="h-28 overflow-hidden rounded-xl bg-[#e9ede4]">{m.type==="video"?<video src={m.url} className="h-full w-full object-cover"/>:<img src={m.url} alt={m.alt} className="h-full w-full object-cover"/>}</div>)}</div></div>}
          {(form.address || target==="contact") && <div className={`plak-preview-card ${target==="contact"?"is-selected":""}`} onClick={()=>pickTarget("contact")}><h3>Onde estamos</h3><p className="mt-2 text-sm">{editable(form.address || "Clique para adicionar o endereço", v=>update("address",v), "plak-inline-paragraph")}</p></div>}
          <div className="pb-7 pt-4 text-center text-[10px] text-[#9aa397]">Feito com <strong>PLAK</strong></div>
        </div>
        <div className="plak-section-inserter" aria-label="Adicionar conteúdo à página">
          <span className="plak-inserter-label">ADICIONAR À PÁGINA</span>
          <div className="plak-inserter-actions">
            <button onClick={() => { addButton(); pickTarget("actions"); }}><Plus size={14}/> Botão</button>
            <button onClick={() => { updateFeatures({ campaign_enabled: true, campaign_title: form.features.campaign_title || "Uma novidade", campaign_text: form.features.campaign_text || "Conte aqui sobre sua oferta ou novidade." }); pickTarget("campaign"); }}><Plus size={14}/> Destaque</button>
            <button onClick={() => { updateFeatures({ testimonials_text: form.features.testimonials_text || "Atendimento excelente!" }); pickTarget("testimonials"); }}><Plus size={14}/> Depoimento</button>
            <button onClick={() => pickTarget("gallery")}><Plus size={14}/> Galeria</button>
            <button onClick={() => pickTarget("catalog")}><Plus size={14}/> Catálogo</button>
            <button onClick={() => { pickTarget("contact"); }}><Plus size={14}/> Contato</button>
          </div>
        </div>
        </div><div className="plak-canvas-foot"><span><Check size={13}/> Edição direta · alterações em tempo real</span><span>/{form.slug || "sua-pagina"}</span></div>
      </main>
      {rightOpen && <aside className="plak-properties"><div className="plak-properties-head"><div><div className="text-[10px] font-bold uppercase tracking-[.16em] text-[#84907e]">Editar seleção</div><h2>{({page:"Página",cover:"Imagem de capa",identity:"Identidade",tagline:"Texto",actions:"Botões e links",gallery:"Galeria",catalog:"Catálogo",campaign:"Destaque",testimonials:"Depoimentos",contact:"Contato"} as Record<Target,string>)[target]}</h2></div><button className="plak-icon-btn" onClick={()=>setRightOpen(false)} title="Recolher painel"><ChevronRight size={18}/></button></div>
        <div className="plak-properties-body">
          {(target==="identity"||target==="tagline") && <><div className="plak-field-group"><label>Nome da página</label><input className={fieldClass} value={form.name} onChange={e=>updateName(e.target.value)} placeholder="Nome da marca"/></div><div className="plak-field-group"><label>Frase de apresentação</label><textarea className={fieldClass} rows={3} value={form.tagline} onChange={e=>update("tagline",e.target.value)} placeholder="Uma frase curta sobre o negócio"/></div><div className="plak-field-group"><label>Endereço da página</label><div className="flex items-center rounded-xl border border-[#dfe5d9] bg-white px-3"><span className="text-sm text-[#98a091]">/</span><input className="min-w-0 flex-1 py-2.5 pl-1 text-sm outline-none" value={form.slug} onChange={e=>update("slug",normalizeSlug(e.target.value))}/></div></div><div className="plak-field-group"><label>Alinhamento</label><div className="grid grid-cols-2 gap-2"><button className={`plak-choice ${layout.text_align==="left"?"selected":""}`} onClick={()=>updateLayout({text_align:"left"})}>Esquerda</button><button className={`plak-choice ${layout.text_align==="center"?"selected":""}`} onClick={()=>updateLayout({text_align:"center"})}>Centralizado</button></div></div><div className="plak-field-group"><label>Fonte</label><select className={fieldClass} value={layout.font_family} onChange={e=>updateLayout({font_family:e.target.value})}>{["Inter","Manrope","Poppins","Montserrat","Playfair Display","Lora","Oswald"].map(x=><option key={x}>{x}</option>)}</select></div><div className="plak-field-group"><label>Tamanho do título · {layout.title_font_size}px</label><input type="range" min="20" max="46" value={layout.title_font_size} onChange={e=>updateLayout({title_font_size:Number(e.target.value)})}/></div><div className="plak-field-group"><label>Tamanho da frase · {layout.tagline_font_size}px</label><input type="range" min="11" max="22" value={layout.tagline_font_size} onChange={e=>updateLayout({tagline_font_size:Number(e.target.value)})}/></div></>}
          {target==="cover" && <><input ref={coverRef} type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f){setCoverFile(f);update("background_image_url",URL.createObjectURL(f));}}}/><button className="plak-upload-tile" onClick={()=>coverRef.current?.click()}><Upload size={18}/><span>Enviar imagem de capa</span></button><div className="plak-field-group"><label>Tratamento</label><select className={fieldClass} value={layout.cover_treatment} onChange={e=>updateLayout({cover_treatment:e.target.value})}><option value="original">Original</option><option value="light">Clareado</option><option value="dark">Escurecido</option><option value="gray">Cinza</option></select></div><div className="plak-field-group"><label>Posição horizontal · {layout.cover_position_x}%</label><input type="range" min="0" max="100" value={layout.cover_position_x} onChange={e=>updateLayout({cover_position_x:Number(e.target.value)})}/></div><div className="plak-field-group"><label>Posição vertical · {layout.cover_position_y}%</label><input type="range" min="0" max="100" value={layout.cover_position_y} onChange={e=>updateLayout({cover_position_y:Number(e.target.value)})}/></div><div className="plak-field-group"><label>Intensidade do filtro</label><input type="range" min="0" max="90" value={layout.cover_opacity} onChange={e=>updateLayout({cover_opacity:Number(e.target.value)})}/></div><button className="plak-secondary-btn w-full justify-center" onClick={()=>logoRef.current?.click()}><Upload size={15}/> Trocar logo</button></>}
          {target==="actions" && <><div className="plak-field-group"><label>WhatsApp (com DDI e DDD)</label><input className={fieldClass} value={form.whatsapp_number} onChange={e=>update("whatsapp_number",e.target.value.replace(/\D/g,""))} placeholder="5511999999999"/></div><div className="plak-field-group"><label>Mensagem automática</label><textarea className={fieldClass} rows={2} value={form.whatsapp_message} onChange={e=>update("whatsapp_message",e.target.value)}/></div><div className="plak-field-group"><label>Instagram</label><input className={fieldClass} value={form.instagram_url} onChange={e=>update("instagram_url",normalizeInstagram(e.target.value))} placeholder="@suaempresa ou URL"/></div><div className="plak-field-group"><label>Link de avaliações Google</label><input className={fieldClass} value={form.google_review_url} onChange={e=>update("google_review_url",e.target.value)} placeholder="https://..."/></div><div className="plak-field-group"><label>Site</label><input className={fieldClass} value={form.website_url} onChange={e=>update("website_url",e.target.value)} placeholder="https://..."/></div><div className="my-4 border-t border-[#e9ede5] pt-4"><div className="mb-3 text-xs font-bold text-[#63705d]">Botões personalizados</div>{form.links.map((link,i)=><div key={i} className="mb-3 rounded-xl border border-[#e2e8dc] p-3"><input className={fieldClass} value={link.label} onChange={e=>change(c=>({...c,links:c.links.map((x,j)=>j===i?{...x,label:e.target.value}:x)}))} placeholder="Texto do botão"/><input className={`${fieldClass} mt-2`} value={link.url} onChange={e=>change(c=>({...c,links:c.links.map((x,j)=>j===i?{...x,url:e.target.value}:x)}))} placeholder="https://..."/><button className="mt-2 flex items-center gap-1 text-xs font-semibold text-red-600" onClick={()=>change(c=>({...c,links:c.links.filter((_,j)=>j!==i)}))}><Trash2 size={13}/> Remover botão</button></div>)}<button className="plak-secondary-btn w-full justify-center" onClick={addButton}><Plus size={15}/> Adicionar botão</button></div><div className="plak-field-group"><label>Cor do botão principal</label><input type="color" className="h-10 w-full rounded-lg border border-[#dfe5d9]" value={form.custom_button_color} onChange={e=>update("custom_button_color",e.target.value)}/></div><div className="plak-field-group"><label>Formato</label><select className={fieldClass} value={layout.button_style} onChange={e=>updateLayout({button_style:e.target.value})}><option value="soft">Suave</option><option value="rounded">Arredondado</option><option value="pill">Pílula</option><option value="square">Quadrado</option><option value="outline">Contorno</option></select></div></>}
          {target==="gallery" && <><input ref={mediaRef} type="file" accept="image/*,video/*" multiple className="hidden" onChange={e=>Array.from(e.target.files||[]).forEach(addMedia)}/><button className="plak-upload-tile" onClick={()=>mediaRef.current?.click()}><Upload size={18}/><span>Adicionar imagens ou vídeos</span></button><p className="mb-3 text-xs text-[#879181]">As imagens aparecem no canvas assim que forem selecionadas.</p>{form.media.map((m,i)=><div key={`${m.url}-${i}`} className="mb-3 flex items-center gap-3 rounded-xl border border-[#e2e8dc] p-2"><div className="h-14 w-14 shrink-0 overflow-hidden rounded-lg bg-[#edf0e8]">{m.type==="video"?<video src={m.url} className="h-full w-full object-cover"/>:<img src={m.url} className="h-full w-full object-cover"/>}</div><div className="min-w-0 flex-1"><input className={`${fieldClass} !px-2 !py-2`} value={m.alt} onChange={e=>change(c=>({...c,media:c.media.map((x,j)=>j===i?{...x,alt:e.target.value}:x)}))}/><button className="mt-1 text-xs font-semibold text-red-600" onClick={()=>change(c=>({...c,media:c.media.filter((_,j)=>j!==i)}))}>Remover</button></div></div>)}</>}
          {target==="page" && <><div className="plak-field-group"><label>Cor de fundo</label><input type="color" className="h-10 w-full rounded-lg border border-[#dfe5d9]" value={form.background_color} onChange={e=>update("background_color",e.target.value)}/></div><div className="plak-field-group"><label>Cor principal</label><input type="color" className="h-10 w-full rounded-lg border border-[#dfe5d9]" value={form.primary_color} onChange={e=>update("primary_color",e.target.value)}/></div><div className="plak-field-group"><label>Cor secundária</label><input type="color" className="h-10 w-full rounded-lg border border-[#dfe5d9]" value={form.secondary_color} onChange={e=>update("secondary_color",e.target.value)}/></div><div className="plak-field-group"><label>Cor do texto do botão</label><input type="color" className="h-10 w-full rounded-lg border border-[#dfe5d9]" value={layout.custom_button_text_color} onChange={e=>updateLayout({custom_button_text_color:e.target.value})}/></div><div className="plak-field-group"><label>Espaçamento</label><select className={fieldClass} value={layout.section_spacing} onChange={e=>updateLayout({section_spacing:e.target.value})}><option value="compact">Compacto</option><option value="comfortable">Confortável</option><option value="airy">Amplo</option></select></div><div className="plak-field-group"><label>Endereço</label><textarea className={fieldClass} rows={3} value={form.address} onChange={e=>update("address",e.target.value)}/></div><div className="plak-field-group"><label>Google Maps</label><input className={fieldClass} value={form.maps_url} onChange={e=>update("maps_url",e.target.value)}/></div></>}
          {target==="campaign" && <><div className="plak-field-group"><label className="flex items-center gap-2"><input type="checkbox" checked={form.features.campaign_enabled} onChange={e=>updateFeatures({campaign_enabled:e.target.checked})}/> Exibir destaque</label></div><div className="plak-field-group"><label>Título</label><input className={fieldClass} value={form.features.campaign_title} onChange={e=>updateFeatures({campaign_title:e.target.value})}/></div><div className="plak-field-group"><label>Descrição</label><textarea className={fieldClass} rows={4} value={form.features.campaign_text} onChange={e=>updateFeatures({campaign_text:e.target.value})}/></div><div className="plak-field-group"><label>Link do destaque</label><input className={fieldClass} value={form.features.campaign_url} onChange={e=>updateFeatures({campaign_url:e.target.value})}/></div></>}
          {target==="catalog" && <><div className="plak-field-group"><label>Título</label><input className={fieldClass} value={form.features.catalog_title||""} onChange={e=>updateFeatures({catalog_title:e.target.value})}/></div><div className="plak-field-group"><label>Subtítulo</label><input className={fieldClass} value={form.features.catalog_subtitle||""} onChange={e=>updateFeatures({catalog_subtitle:e.target.value})}/></div><p className="text-xs leading-5 text-[#818d7c]">Os produtos e serviços podem ser gerenciados pela área de catálogo do projeto. Esta tela mostra uma prévia em tempo real.</p></>}
          {target==="testimonials" && <><div className="plak-field-group"><label>Título</label><input className={fieldClass} value={form.features.testimonials_title||""} onChange={e=>updateFeatures({testimonials_title:e.target.value})}/></div><div className="plak-field-group"><label>Depoimentos (um por linha)</label><textarea className={fieldClass} rows={6} value={form.features.testimonials_text} onChange={e=>updateFeatures({testimonials_text:e.target.value})}/></div></>}
          {target==="contact" && <><div className="plak-field-group"><label>Endereço</label><textarea className={fieldClass} rows={3} value={form.address} onChange={e=>update("address",e.target.value)}/></div><div className="plak-field-group"><label>Google Maps</label><input className={fieldClass} value={form.maps_url} onChange={e=>update("maps_url",e.target.value)}/></div><div className="plak-field-group"><label>Site</label><input className={fieldClass} value={form.website_url} onChange={e=>update("website_url",e.target.value)}/></div></>}
          <div className="mt-6 rounded-xl bg-[#f1f5e9] p-3 text-xs leading-5 text-[#6d7c61]">Edite no próprio canvas ou use os controles deste painel. As mudanças aparecem imediatamente na página.</div>
        </div><button className="plak-panel-collapse" onClick={()=>setRightOpen(false)}><ChevronRight size={16}/><span>Recolher painel</span></button></aside>}
      {!rightOpen && <button className="plak-edge-toggle right-edge" onClick={()=>setRightOpen(true)} title="Abrir propriedades"><ChevronLeft size={17}/></button>}
    </div>
    <input ref={logoRef} type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f){setLogoFile(f);update("logo_url",URL.createObjectURL(f));}}}/>
  </div></AdminShell>;
}
