import type { Business, BusinessLink, LayoutConfig } from "@/lib/types";
import type { CanvasElement } from "./freeCanvasModel";

interface Props { business: Business; links: BusinessLink[]; elements: CanvasElement[]; layout?: LayoutConfig; onClick?: (target: string) => void; }

export default function FreePageRenderer({ business, links, elements, layout, onClick }: Props) {
  const visible = elements.filter((element) => element.visible !== false).sort((a, b) => a.zIndex - b.zIndex);
  return <main className="min-h-screen px-4 py-8" style={{ background: business.background_color, fontFamily: layout?.font_family || "Inter" }}><div className="relative mx-auto w-full max-w-[390px] overflow-hidden rounded-[28px] shadow-[0_22px_70px_rgba(35,55,40,.14)]" style={{ minHeight: 844, background: business.background_color }}>{business.background_image_url && <div className="absolute inset-0 bg-cover bg-center opacity-30" style={{ backgroundImage: `url(${business.background_image_url})` }} />}{visible.map((element) => { const style: React.CSSProperties = { position: "absolute", left: `${element.x}%`, top: `${element.y}%`, width: `${element.width}%`, height: `${element.height}%`, zIndex: element.zIndex, opacity: element.opacity, transform: `rotate(${element.rotation}deg)`, padding: element.padding ?? 12, borderRadius: element.radius ?? 12, background: element.background || "transparent", color: element.text_color || "#263b3a", fontSize: element.fontSize, fontFamily: element.fontFamily, fontWeight: element.fontWeight, textAlign: element.align || "left", border: `${element.borderWidth || 0}px solid ${element.borderColor || "transparent"}`, boxSizing: "border-box", overflow: "hidden", whiteSpace: "pre-wrap", wordBreak: "break-word" };
    const body = element.type === "image" && element.image_url ? <img src={element.image_url} alt={element.title || "Imagem"} className="h-full w-full" style={{ objectFit: element.objectFit || "cover" }} /> : element.type === "logo" ? <img src={business.logo_url || ""} alt={`Logo de ${business.name}`} className="h-full w-full object-contain" /> : element.type === "shape" ? null : <><strong className="block">{element.title}</strong><span className="block">{element.text}</span></>;
    const content = element.type === "button" && element.url ? <a href={element.url} onClick={() => onClick?.(`block:${element.id}`)} target="_blank" rel="noopener noreferrer" className="flex h-full w-full items-center justify-center no-underline" style={{ color: "inherit" }}>{body}</a> : body;
    return <div key={element.id} style={style}>{content}</div>; })}</div><footer className="mx-auto mt-5 max-w-[390px] text-center text-xs text-[#879487]">Feito com PLAK</footer></main>;
}
