import { useEffect, useState } from "react";
import { BarChart3, LayoutDashboard, LogOut, Menu, Plus, ShieldCheck, X } from "lucide-react";
import { Link, useLocation } from "wouter";
import { useAuth } from "@/lib/supabase";
import { currentProfile } from "@/lib/data";
import type { Profile } from "@/lib/types";
import { BrandLogo } from "./BrandLogo";

export function AdminShell({ children }: { children: React.ReactNode }) { const { user, loading, signOut } = useAuth(); const [profile, setProfile] = useState<Profile | null>(null); const [open, setOpen] = useState(false); const [location] = useLocation();
  useEffect(() => { if (user) currentProfile().then(setProfile).catch(() => setProfile(null)); else setProfile(null); }, [user]);
  if (loading) return <div className="min-h-screen grid place-items-center bg-[#f7f5f0]"><div className="loader-dot" /></div>;
  if (!user) return <div className="min-h-screen grid place-items-center bg-[#f7f5f0] px-6 text-center"><div><BrandLogo /><h1 className="font-display mt-8 text-3xl font-semibold text-[#183039]">Sessão necessária</h1><p className="mt-3 max-w-sm text-sm leading-6 text-[#7c8982]">Entre na sua conta para acessar o painel de gestão.</p><Link href="/login" className="mt-6 inline-flex rounded-full bg-[#14252c] px-5 py-3 text-sm font-bold text-white">Ir para login</Link></div></div>;
  const links = [{ href: "/admin", label: "Visão geral", icon: LayoutDashboard }, { href: "/admin/new", label: "Novo cliente", icon: Plus }, ...(profile?.role === "admin" ? [{ href: "/admin/accounts", label: "Contas", icon: ShieldCheck }] : [])];
  return <div className="min-h-screen bg-[#f7f5f0] text-[#183039]"><aside className={`fixed inset-y-0 left-0 z-40 flex w-[278px] flex-col bg-[#14252c] px-4 py-5 text-[#f7f5f0] shadow-2xl transition-transform lg:translate-x-0 ${open ? "translate-x-0" : "-translate-x-full"}`}><div className="flex items-center justify-between px-2"><BrandLogo inverse /><button className="grid h-9 w-9 place-items-center rounded-xl text-white/60 hover:bg-white/10 lg:hidden" onClick={() => setOpen(false)} aria-label="Fechar menu"><X className="h-5 w-5" /></button></div><div className="mt-10 px-2 text-[10px] font-bold uppercase tracking-[.2em] text-[#8fa89a]">Painel de gestão</div><nav className="mt-3 space-y-1">{links.map(item => <Link key={item.href} href={item.href} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-2xl px-3 py-3 text-sm font-semibold transition ${location === item.href ? "bg-[#d7f56c] text-[#183039] shadow-[0_10px_22px_rgba(215,245,108,.12)]" : "text-[#c6d3cb] hover:bg-white/8 hover:text-white"}`}><item.icon className="h-4 w-4" />{item.label}</Link>)}</nav><div className="mt-auto rounded-2xl border border-white/10 bg-white/5 p-3"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#d7f56c] text-xs font-bold text-[#183039]">{(user.user_metadata?.full_name || user.email || "U").slice(0, 1).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{user.user_metadata?.full_name || "Administrador"}</p><p className="truncate text-xs text-[#9fb2aa]">{user.email}</p></div></div><button onClick={signOut} className="mt-3 flex w-full items-center gap-2 rounded-xl px-2 py-2 text-xs font-bold text-[#c6d3cb] hover:bg-white/10 hover:text-white"><LogOut className="h-3.5 w-3.5" />Sair</button></div></aside><div className="lg:pl-[278px]"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-[#e3e4dc]/80 bg-[#f7f5f0]/90 px-4 backdrop-blur-xl sm:px-7 lg:hidden"><button onClick={() => setOpen(true)} className="grid h-10 w-10 place-items-center rounded-xl bg-white shadow-sm" aria-label="Abrir menu"><Menu className="h-5 w-5" /></button><BrandLogo compact /><span className="w-10" /></header><main className="mx-auto max-w-[1400px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10">{children}</main></div>{open && <button className="fixed inset-0 z-30 bg-[#14252c]/35 lg:hidden" onClick={() => setOpen(false)} aria-label="Fechar menu" />}</div>; }
