create extension if not exists pgcrypto;

do $$ begin create type public.business_status as enum ('draft','published','inactive'); exception when duplicate_object then null; end $$;
do $$ begin create type public.access_status as enum ('pending','approved','revoked'); exception when duplicate_object then null; end $$;
do $$ begin create type public.user_role as enum ('user','admin'); exception when duplicate_object then null; end $$;
do $$ begin create type public.analytics_event_type as enum ('view','click'); exception when duplicate_object then null; end $$;
do $$ begin create type public.device_type as enum ('mobile','tablet','desktop'); exception when duplicate_object then null; end $$;
do $$ begin create type public.analytics_source as enum ('instagram','whatsapp','google','placa','direct','other'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, email text, role public.user_role not null default 'user', access_status public.access_status not null default 'pending', is_protected boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.businesses (id uuid primary key default gen_random_uuid(), name varchar(160) not null, slug varchar(120) not null unique, logo_url text, tagline varchar(255) not null default 'Olá! Como podemos ajudar?', google_review_url text, whatsapp_number varchar(40), whatsapp_message varchar(255), instagram_url text, website_url text, address text, maps_url text, primary_color varchar(7) not null default '#0F766E', secondary_color varchar(7) not null default '#F2B84B', background_color varchar(7) not null default '#FBFAF6', background_image_url text, standard_button_color varchar(7) not null default '#FFFFFF', custom_button_color varchar(7) not null default '#FFFFFF', seo_title text, seo_description text, seo_image_url text, status public.business_status not null default 'draft', published_at timestamptz, created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.business_links (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, label varchar(80) not null, url text not null, kind varchar(20) not null default 'site', color varchar(7) not null default '#FFFFFF', position integer not null default 0);
create table if not exists public.business_media (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, type varchar(10) not null check (type in ('image','video')), url text not null, storage_path text, alt varchar(160) not null default '', position integer not null default 0);
create table if not exists public.analytics_events (id bigint generated always as identity primary key, business_id uuid not null references public.businesses(id) on delete cascade, event_type public.analytics_event_type not null, target varchar(120) not null default 'page', source public.analytics_source not null default 'direct', device_type public.device_type not null default 'desktop', referrer text, created_at timestamptz not null default now());
create index if not exists businesses_status_idx on public.businesses(status); create index if not exists business_links_business_idx on public.business_links(business_id, position); create index if not exists business_media_business_idx on public.business_media(business_id, position); create index if not exists analytics_business_date_idx on public.analytics_events(business_id, created_at desc);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id, full_name, email) values (new.id, new.raw_user_meta_data->>'full_name', new.email) on conflict (id) do update set email = excluded.email; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security; alter table public.businesses enable row level security; alter table public.business_links enable row level security; alter table public.business_media enable row level security; alter table public.analytics_events enable row level security;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin' and access_status = 'approved'); $$;
drop policy if exists profiles_self_or_admin on public.profiles; create policy profiles_self_or_admin on public.profiles for select using (id = auth.uid() or public.is_admin());
drop policy if exists profiles_admin_write on public.profiles; create policy profiles_admin_write on public.profiles for update using (public.is_admin()) with check (public.is_admin());
drop policy if exists profiles_admin_delete on public.profiles; create policy profiles_admin_delete on public.profiles for delete using (public.is_admin());
drop policy if exists business_public_read on public.businesses; create policy business_public_read on public.businesses for select using (status = 'published' or public.is_admin());
drop policy if exists business_admin_write on public.businesses; create policy business_admin_write on public.businesses for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists links_public_read on public.business_links; create policy links_public_read on public.business_links for select using (exists(select 1 from public.businesses b where b.id = business_id and (b.status = 'published' or public.is_admin())));
drop policy if exists links_admin_write on public.business_links; create policy links_admin_write on public.business_links for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists media_public_read on public.business_media; create policy media_public_read on public.business_media for select using (exists(select 1 from public.businesses b where b.id = business_id and (b.status = 'published' or public.is_admin())));
drop policy if exists media_admin_write on public.business_media; create policy media_admin_write on public.business_media for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists analytics_insert_public on public.analytics_events; create policy analytics_insert_public on public.analytics_events for insert with check (true);
drop policy if exists analytics_admin_read on public.analytics_events; create policy analytics_admin_read on public.analytics_events for select using (public.is_admin());

insert into storage.buckets (id, name, public) values ('business-assets', 'business-assets', true) on conflict (id) do nothing;
drop policy if exists asset_public_read on storage.objects; create policy asset_public_read on storage.objects for select using (bucket_id = 'business-assets');
drop policy if exists asset_admin_insert on storage.objects; create policy asset_admin_insert on storage.objects for insert with check (bucket_id = 'business-assets' and public.is_admin());
drop policy if exists asset_admin_update on storage.objects; create policy asset_admin_update on storage.objects for update using (bucket_id = 'business-assets' and public.is_admin());
drop policy if exists asset_admin_delete on storage.objects; create policy asset_admin_delete on storage.objects for delete using (bucket_id = 'business-assets' and public.is_admin());
